### ISSUE TITLE
improve the sliding animations

### ISSUE THREAD

**Issue by hannah-maria** [aslams2020/Stark-Tech-Portfolio#10]
- when the website loads, the text and image slides in at different times(slightly delayed), would like to make it make that equal

Kindly assign me this issue with tags gssoc ext, hactoberfest and level tags

**Comment by hannah-maria** [comment]
Kindly add the levels aswell :)

**Comment by aslams2020** [comment]
Levels are added based on the work you did. Go ahead

**Comment by aslams2020** [comment]
@hannah-maria Are u willing to work on it ?
