### ISSUE TITLE
Links for videos.

### ISSUE THREAD

**Issue by akansha-02** [aslams2020/Stark-Tech-Portfolio#100]
There is no link attached to watch movie or any related videos to redirect it to another page.
![Screenshot 2024-10-03 004838](https://github.com/user-attachments/assets/b8842d73-fbf4-4f06-835e-6accac3d7dab)

Please assign me this issue under gssoc'24 EXTENDED and hacktoberfest.

**Comment by aslams2020** [comment]
Already assinged to someone else.
