### ISSUE TITLE
Improve styling of buttons and font

### ISSUE THREAD

**Issue by tanishraj7** [aslams2020/Stark-Tech-Portfolio#101]
![image](https://github.com/user-attachments/assets/204ef400-f409-4896-b74a-ae90e642cb1b)
wanted to add 3d motion effect

**Comment by SHRAVANIc01** [comment]
I want  to  @contribute.[@tanishraj7 ]

**Comment by pameladeysarkar2003** [comment]
i want to contribute @aslams2020

**Comment by aslams2020** [comment]
@tanishraj7 Assigning you. 

Style the below three buttons only, make sure to follow website theme.
![image](https://github.com/user-attachments/assets/b3cbaaa7-ba30-4f7e-9c48-a480fc92d294)

![image](https://github.com/user-attachments/assets/f0641a4c-1de4-4735-b1c3-651a6680055d)

**Comment by aslams2020** [comment]
@tanishraj7 Are u willing to work on it? please let me know. as soon as possible

**Comment by tanishraj7** [comment]
Yes yes it will be done by tomorrow
