### ISSUE TITLE
Improve responsiveness

### ISSUE THREAD

**Issue by SurajSG23** [aslams2020/Stark-Tech-Portfolio#109]
Hey, i noticed that in your header part the logo of the ironman is disappearing once website width is decreased,

![image](https://github.com/user-attachments/assets/bd466b0d-e255-4033-896a-c9ae53a8ddf4)

i would like to change this and make it more visible which thus improves the UI of your website.

Please let me work on it and fix it under GSSoC and Hacktober fest.🙏

**Comment by aslams2020** [comment]
@SurajSG23 Go ahead. Make sure it's responsive too

**Comment by aslams2020** [comment]
Assigned u.
Level will be given based on the work. So dw about it.

**Comment by SurajSG23** [comment]
sure thank you, I will work on it now !!
