### ISSUE TITLE
Add more Marvel superheroes to this page Like Spiderman

### ISSUE THREAD

**Issue by rutikakengal** [aslams2020/Stark-Tech-Portfolio#11]
I like to Add More Superheroes to the project, give more Information to Marvel superheroes And their commics related info like superheroes as Spiderman,Wolverine,Captain America,black Window,Thor,Doctor Strange . Assign me I like to work On it

**Comment by AyutheCoder** [comment]
I would like to work over it,please provide label to it under GSSOC EXT 24 and Hactoberfest
