### ISSUE TITLE
Adding a Comics Section in the website

### ISSUE THREAD

**Issue by AyutheCoder** [aslams2020/Stark-Tech-Portfolio#111]
@aslams2020  Sir,I can add a new option in navbar of upcoming events of ironman with countdown times or a gallery section as required, please assign this task to me under GSSoc Ext 24 and hactoberfest with label .

**Comment by AyutheCoder** [comment]
@aslams2020 Sir can you please assign this work to me under GSSoc Ext,Hactoberfest

**Comment by AyutheCoder** [comment]
@aslams2020  Sir,please have a review to the issue,can you please assign this tak to me?

**Comment by AyutheCoder** [comment]
Sir,I can add the following things as required-
1.)Movie and Series Premieres: Information on upcoming films or TV series featuring Iron Man, including trailers and premiere dates.
2.)Conventions and Expos: Details about comic conventions, expos, or fan events where Iron Man will be featured, including panels and signings.
3.)Fan Events: Information about local fan meet-ups, watch parties for Iron Man-related movies, or themed events.
4.)-Merchandise Launches: Announcements for new Iron Man merchandise, including toys, collectibles, and apparel.
5.)-Comic Book Releases: Announcements for new Iron Man comic issues or graphic novels, including release dates and pre-order links.
@aslams2020 Sir,please assign this task to me under GSSoc Ext and hactoberfest

**Comment by aslams2020** [comment]
Can we do something like "Comics" Section in the navbar ..? 

That Comics Page can include existing comics books maybe some popular ones...what do u think? Let me know if u can work on it. 

(Refer to the "Watch video" page in our website to get an idea of format we need)

**Comment by AyutheCoder** [comment]
@aslams2020 Yes Sir,I can add an option in navbar that include some existing comic book names(the popular ones),with picture and short description.

**Comment by AyutheCoder** [comment]
Can you please assign this task to me with GSSOc Ext and hactoberfest label.

**Comment by aslams2020** [comment]
> @aslams2020 Yes Sir,I can add an option in navbar that include some existing comic book names(the popular ones),with picture and short description.
> 

Okay, make sure to take reference from the existing movies page.
Follow the website theme.

**Comment by AyutheCoder** [comment]
Ok Sir,thankyou
