### ISSUE TITLE
Navbar overlapping body text 

### ISSUE THREAD

**Issue by sehajsomal5** [aslams2020/Stark-Tech-Portfolio#112]
The navigation bar overlaps the body content when the page is loaded, particularly the section below the navbar. This reduces readability and negatively affects the user experience. The overlap occurs with the body text, as shown in the screenshot.

![image](https://github.com/user-attachments/assets/a780162e-a8df-4f4b-8f66-925be883678e)

**_Steps to reproduce:_**

Open the page in any web browser.
Observe that the navbar covers part of the text content directly below it.

**_Expected behavior:_**
 The body content should not be hidden behind the navbar. The navbar should either be fixed at the top without covering the content or there should be appropriate spacing (padding/margin) between the navbar and the body content.

**_Possible Solution:_**

Add appropriate padding or margin to the body content below the navbar.

**Comment by sehajsomal5** [comment]
@aslams2020 Kindly assign me the issue

**Comment by tulikaa25** [comment]
@aslams2020 Please assign this issue to me.Kindly attach the labels

**Comment by Ishajain0** [comment]
@aslams2020 Please assign this task to me. I would like to work on it ....

**Comment by vinay7376** [comment]
Please assign this issue to me.Kindly attach the labels

**Comment by sehajsomal5** [comment]
@aslams2020 Please assign me
