### ISSUE TITLE
"Watch Video Feature Not Functioning Properly"

### ISSUE THREAD

**Issue by praveenarjun** [aslams2020/Stark-Tech-Portfolio#114]
Enhancement: Add Iron Man Trailer Button

Description:
I am going to create a JavaScript file that will add functionality to a button. When this button is clicked, it will insert an anchor tag that opens a link to the best Iron Man introduction trailer. The goal is to generate curiosity and excitement about the Iron Man movies by showcasing Tony Stark's iconic character and high-tech innovations.

Purpose:
This enhancement will provide an engaging experience for visitors of the portfolio website by allowing them to watch a captivating trailer. This feature aims to reflect the sleek and modern interface inspired by Tony Stark, aligning with the high-tech and innovative spirit of Stark Industries.

Technical Details:

    JavaScript: Handle the button click event to add an anchor tag.
    HTML/CSS: Ensure the anchor tag is styled appropriately and integrates seamlessly with the existing design.

This feature will enhance the portfolio's interactivity and make it more appealing to visitors.

**Comment by praveenarjun** [comment]
Going to add this vedio link https://www.youtube.com/watch?v=sYOYFywcMJg
But I need some benefits so pls give me labels it will improve my rank

**Comment by aslams2020** [comment]
Already assigned to #8
