### ISSUE TITLE
Requesting re-assignment as prev acc suspended 

### ISSUE THREAD

**Issue by ghost** [aslams2020/Stark-Tech-Portfolio#119]
My previous acc got suspended so my issue is also suspended. This was assigned to me, kindly reassign it so i can work on it. 
![Screenshot_2024-10-03-17-54-23-54_e307a3f9df9f380ebaf106e1dc980bb6](https://github.com/user-attachments/assets/e41c9bc8-7421-4142-ab3b-0414319b77ac)

**Comment by aslams2020** [comment]
@hana-maria Can you share the screenshot of the email of PR that was merged earlier? With the PR no.

(You can just search repo name there, you'll get it.)

**Comment by hana-maria** [comment]
@aslams2020 
![Screenshot_2024-10-04-14-10-52-18_e307a3f9df9f380ebaf106e1dc980bb6](https://github.com/user-attachments/assets/01371905-804c-4526-9710-fddcd38772d9)
