### ISSUE TITLE
Contact Section appearance enhancement 

### ISSUE THREAD

**Issue by shimmer12** [aslams2020/Stark-Tech-Portfolio#120]
-
- I want to improve the appearance of the contact section to make it consistent.
- Adjust the text alignment on the homepage so that it remains consistent when clicking on the image.

![Screenshot 2024-10-03 170726](https://github.com/user-attachments/assets/0d0020bf-23ea-4ea4-99fc-6517211d8b2d)
![Screenshot 2024-10-03 172155](https://github.com/user-attachments/assets/72ddb42b-9711-45af-b1ed-388779b63030)
![Screenshot 2024-10-03 172141](https://github.com/user-attachments/assets/7f2ef09d-5ada-43fe-8765-ef811a2162a8)

@aslams2020  Please assign this issue to me under GSSOC EXTd and Hacktoberfest accepted tags.
thank you !

**Comment by nishtha-902** [comment]
@aslams2020 please assign me this issue I can solve it very easily

**Comment by shimmer12** [comment]
@aslams2020 please assign me the issue I have made changes on my side, just need to add PR

**Comment by aslams2020** [comment]
Hi @shimmer12 
The Contact page is assigned to other contributor already.

You can still raise new issues.
