### ISSUE TITLE
Add newsletter section 

### ISSUE THREAD

**Issue by kaushalendra0812** [aslams2020/Stark-Tech-Portfolio#121]
Hey Aslam ! 
I would like to contribute to your project by adding the section of FAQ's.

Solution : Add a section where user can subscribe to the newsletter which provides the latest information. 

Please assign me this issue under the labels of Gssoc-extd, hacktoberfest, hacktoberfest-accepted and relevant level.

![Screenshot 2024-10-03 200543](https://github.com/user-attachments/assets/4840a7f6-fce7-4104-be46-4a5e50a434ff)

**Comment by Ishajain0** [comment]
please assign this take to me .I would like to work on it .

**Comment by pameladeysarkar2003** [comment]
please assign me with this task @aslams2020
