### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by NandhikaM** [aslams2020/Stark-Tech-Portfolio#122]
I want to optimize the performance of the website in terms of website's loading speed.

**Comment by aslams2020** [comment]
Can you elaborate. 
How will u approach in brief?

**Comment by NandhikaM** [comment]
Performance optimization can be done by implementing lazy loading attribute to images. By doing so images are only loaded when they enter the user's viewport. Additionally I would also want to implement scroll-to top and dark mode toggling button if assigned.
