### ISSUE TITLE
change in font size

### ISSUE THREAD

**Issue by Laxmi123-coder** [aslams2020/Stark-Tech-Portfolio#13]
the font size are all different plz assign to make it more attractive

**Comment by Gaurav075** [comment]
Please assign this issue to me.

**Comment by Laxmi123-coder** [comment]
i find it first so please assign me

**Comment by riyarane46** [comment]
hii @aslams2020  i believe i can do this task efficiently as i have a strong hold over css styling. could you please assign me this task under GSSoC24 extd.

**Comment by Laxmi123-coder** [comment]
this is my issue so assign me if you want to make it more attractive and responsive
