### ISSUE TITLE
Contradiction between navbar and activity

### ISSUE THREAD

**Issue by synakr** [aslams2020/Stark-Tech-Portfolio#131]
The website looks cool but there are some issues regarding the behavior of the navbar like
1. the navbar is not fixed in the home but fixed in appearance 
(solution is it should be either fixed or normal, but giving it a disappearing transition while scrolling down would seem to be pretty amazing)
2. in the appearance page initially at the top of the page "home" in navbar is activated while "contacts" is activated at the bottom

These should be resolved to make the website more uniform, and i'd be very happy to work on that for GSSoC EXTD 2024
Thank you!

**Comment by aslams2020** [comment]
@synakr Go ahead. Assigning you.

Level will be assigned based on the work, so dw abt it.

**Comment by ghostmonk017** [comment]
@aslams2020 can i also contribute in this issue

**Comment by synakr** [comment]
@aslams2020 Thank you very much! Grateful!
