### ISSUE TITLE
[BUG] in contact page, in the section of "Enter your name " there are some bug which may include digits in name

### ISSUE THREAD

**Issue by anish013326** [aslams2020/Stark-Tech-Portfolio#132]
#### There is a bug on the contact page in the "Enter your name" section that allows users to input digits into the name field. This issue can lead to confusion, as names typically do not contain numbers. To fix this, input validation should be implemented to restrict the field to alphabetic characters only. Additionally, providing users with clear instructions on acceptable input can enhance user experience and ensure that names are entered correctly.

![image](https://github.com/user-attachments/assets/01f5c953-33fd-48f0-8926-74cdbf659186)

**Comment by aslams2020** [comment]
@anish013326 Good. You can work on this.
Also, Could you please add the Label above input field (i.e, Your name, Your Email, Phone Number)

**Comment by itsaryan917** [comment]
i want to work on this issue.

**Comment by aslams2020** [comment]
> i want to work on this issue.

Already assigned to @anish013326.

@itsaryan917 You can still find and raise new issues.
