### ISSUE TITLE
Issue in Contact me mobile number 

### ISSUE THREAD

**Issue by ghostmonk017** [aslams2020/Stark-Tech-Portfolio#133]
<img width="1440" alt="Screenshot 2024-10-04 at 6 39 00 AM" src="https://github.com/user-attachments/assets/49068bec-baa5-493b-980d-14f1070bcfdd">

In this , while using the up and down arrow key only digits are increasing by one. There i can add the country code.

<img width="1440" alt="Screenshot 2024-10-04 at 6 38 47 AM" src="https://github.com/user-attachments/assets/f45d1fb8-4c47-473d-9398-0c94312f0e83">

I can add limit of ten digits to mobile number.
@aslams2020 let me contribute to it , It will be my first open source contribution...

**Comment by vinay7376** [comment]
I will solve this problem, please give it to us

**Comment by pameladeysarkar2003** [comment]
please assign me with this task @aslams2020
