### ISSUE TITLE
Feature: Want to add Easter Eggs

### ISSUE THREAD

**Issue by Tamanna225** [aslams2020/Stark-Tech-Portfolio#136]
I want to add some easter eggs which would display some hidden messages or change some animations when user interact with specific elements.

**Comment by aslams2020** [comment]
Can you provide any example similar to your idea? I didn't get it completely.

**Comment by Tamanna225** [comment]
Hi @aslams2020 Just following up to see if you’ve had a chance to review my explanation. I’d appreciate your thoughts.

**Comment by aslams2020** [comment]
@Tamanna225 Will get back to you regarding this.
Till then you can find new issues.

**Comment by Tamanna225** [comment]
Sure. 
Thanks for the update.

**Comment by aslams2020** [comment]
@Tamanna225 I would like you to implement following ideas proposed by u - 

1. Hidden Clickable link
2. Time-Based Message - like You're true Iron Man Fan Here is a fun fact about Iron man

Please make sure that it will not disturb the user while using the website, it should be consistent and well-suited for the website,
Good luck!

**Comment by aslams2020** [comment]
@Tamanna225 Are u done with it? if not please start working on it

**Comment by aslams2020** [comment]
please let me know

**Comment by aslams2020** [comment]
@Tamanna225 Okay.
