### ISSUE TITLE
Navbar link not highlighting correctly 

### ISSUE THREAD

**Issue by vizzv** [aslams2020/Stark-Tech-Portfolio#138]
On vercel deployement, When I click on Appearances it highlights Home in navbar It should highlight Appearances.

![Screenshot 2024-10-04 135134](https://github.com/user-attachments/assets/0929d611-257f-4fce-8177-3eaebc97e4b3)

It is easy fix.
I want to work on it .

**Comment by pameladeysarkar2003** [comment]
please assign me with this task @aslams2020
