### ISSUE TITLE
UI, Nav bar functionality, Search bar not functionality

### ISSUE THREAD

**Issue by bvvivek6** [aslams2020/Stark-Tech-Portfolio#14]
The height of the nav bar can be lowered and the ui of the contact section can be improved. The ICON can be linked to the home page of the website leading to improved UX. Search functionality is not responding.

The navbar button does not tell me on which page im. Home button is highlighted but when on other sections its not.

I would like to work of these issues. Please assign me this project.

**Comment by aslams2020** [comment]
@bvvivek6 You can start Working on the Navbar Task Only. 
Assigning you

**Comment by bvvivek6** [comment]
> @bvvivek6 You can start Working on the Navbar Task Only. 
> Assigning you

Okay!Thank you
