### ISSUE TITLE
Add Back to top button in ALL Pages

### ISSUE THREAD

**Issue by saadgibawa** [aslams2020/Stark-Tech-Portfolio#140]
Hi! @aslams2020 
I recently added back to top button in this project but now i noticed that the appearances section also lacks that button and i want to add the button there also. Please assign me this.

**Comment by aslams2020** [comment]
@saadgibawa 
Make sure to integrate the scroll to top button in all the pages 
I.e, **`Appearances`**, **`Movies page`** and **`Watch video`** page.

Assigning u.

**Comment by saadgibawa** [comment]
@aslams2020 Got it. thanks!

**Comment by saadgibawa** [comment]
@aslams2020 Should I try different button designs or keep it the same as the one on homepage?

**Comment by aslams2020** [comment]
You can keep it the same as it is in homepage for maintaining consistency.

( But if you have some other better idea, feel free to tell me and implement )

**Comment by aslams2020** [comment]
All the three pages should have the same Button. So please take a note of it.

**Comment by saadgibawa** [comment]
@aslams2020 Sure
I wanted to try this arc reactor thing. Just have a look on what it looks like and let me know what you think.
![Screenshot 2024-10-04 183417](https://github.com/user-attachments/assets/4a2138bb-1e61-44f5-a63e-4f2342a37844)

**Comment by aslams2020** [comment]
It's good..but maybe if something red themed button would be more suitable?

**Comment by saadgibawa** [comment]
Okay, let's stick with the previous one! It complements the red theme and matches the Iron Man logo in the header nicely.

**Comment by Raj-Aditya-27** [comment]
Hi @aslams2020,

I just went through this website and noticed that the "Back to Top" button moves rapidly to the top, which is not pleasing for user experience. Please assign this issue to me, and I can fix it.

You can refer to my previous project where I implemented a more user-friendly "Back to Top" functionality.
https://raj-aditya-27.github.io/SarvottamSamachar/
