### ISSUE TITLE
Proposal : Enhancing the UI of contact section.

### ISSUE THREAD

**Issue by AbhijitMotekar99** [aslams2020/Stark-Tech-Portfolio#141]
Enhanced the UI of the contact section by improving the color combination to create a visually appealing and user-friendly design. The updated color scheme ensures better readability and aligns with the overall aesthetic of the website.

**Comment by tulikaa25** [comment]
Please assign this issue to me.I would make the form visually appealing and user interactive. @aslams2020

**Comment by pameladeysarkar2003** [comment]
please assign me with this task @aslams2020
