### ISSUE TITLE
Homepage text and alignment issue 

### ISSUE THREAD

**Issue by Kavish-Paraswar** [aslams2020/Stark-Tech-Portfolio#145]
Upon hovering over the main text, the size of the box changes, which is unnecessary. Additionally, the buttons, along with the text, require proper alignment. Please remove the hover effect from the homepage's main image and text.
![image](https://github.com/user-attachments/assets/716c8b60-a172-4d96-85de-ad5dceff1575)
Given my strong background in HTML, CSS, and JavaScript, I would like to request this task be assigned to me. I intend to mark this under the GSoC extended projects.

**Comment by pameladeysarkar2003** [comment]
please assign me with this task @aslams2020
