### ISSUE TITLE
Aligning more boxes in apperance page

### ISSUE THREAD

**Issue by Kavish-Paraswar** [aslams2020/Stark-Tech-Portfolio#146]
I would like to request adjustments to the movie flexboxes to reduce their width and height, enhancing their overall appeal

![image](https://github.com/user-attachments/assets/134a7006-dd06-4c4d-8bac-842da2ca1820)

 Additionally, I recommend removing the last block before the copyright section on the appearances page, as it disrupts the uniformity of the UI.
![image](https://github.com/user-attachments/assets/c9a350fc-7fc4-425d-9803-ba280f2f252e)

Given my strong background in HTML, CSS, and JavaScript, I would like to request this task be assigned to me. I intend to mark this under the GSoC extended projects.

**Comment by ravi-kumar2003** [comment]
I came across this issue, and I would love to help contribute to resolving it.

**Comment by pameladeysarkar2003** [comment]
please assign me with this task @aslams2020 i would like to contribute to it
