### ISSUE TITLE
Redesign the hero/landing/home of website. Improve font and colors.

### ISSUE THREAD

**Issue by swatified** [aslams2020/Stark-Tech-Portfolio#147]
Hey I just realised that the text align and image placeholder and bg dont go well together. I want to fix those hiccups in the landing page and make it look iron man like but still seamless and pretty.
 
**PROPOSED SOLUTION**
![Frame 1](https://github.com/user-attachments/assets/c3a56105-e1b7-43cb-987f-0d03b37266a8)

**CURRENT VERSION**
![Screenshot 2024-10-04 185919](https://github.com/user-attachments/assets/00b89786-70ae-4b05-be0e-c64eaf0ecaeb)

Want to improve such way whole website's ui.

**Comment by swatified** [comment]
@pathak-arvind @AtaanshAhlawat please assign this to me and and gssoc-ext, hacktoberfest and level 3 tags. So that I can start working as quick as possible

**Comment by aslams2020** [comment]
@swatified 
I would like you to work on only this part as in the below image. 
(Don't change anything in the navbar ..Keep it as original)

![image](https://github.com/user-attachments/assets/c31af6f7-8e69-4743-9d71-c30f209dbf98)

**Comment by aslams2020** [comment]
Assigning you to do the task i explained above.
go ahead.

**Comment by swatified** [comment]
@aslams2020 Okay sure. Can I also fix the alignment of footer form and reduce text in second image so as its more readable and engaging? I could do some content-writing improvement there. 
![Screenshot 2024-10-04 215600](https://github.com/user-attachments/assets/8f9b0bbc-05d0-4759-9ee5-a2db9c46dc88)
![Screenshot 2024-10-04 215628](https://github.com/user-attachments/assets/10710195-9656-404f-a7a7-5b14de1b82a7)

Let me know.

**Comment by aslams2020** [comment]
No, Let it be. 
Just make the changes for herosection as i mentioned above
