### ISSUE TITLE
Bug : Add contact form submission functionality

### ISSUE THREAD

**Issue by AkankshaSinghK** [aslams2020/Stark-Tech-Portfolio#148]
@aslams2020 
I would like to implement functionality in the 'Contact Us' form to send an email upon clicking the 'Submit' button to receive form data.

For resolving this issue i need your mail id on which you want to receive your contact form data.

![image](https://github.com/user-attachments/assets/bcf23cfe-2d87-43f9-a56c-25268c41348e)

Kindly assign this issue to me and add gssoc-extd and hactoberfest tags and level it.

**Comment by pameladeysarkar2003** [comment]
please assign me with this task @aslams2020

**Comment by aslams2020** [comment]
Go ahead! sorry for the delay. 
make sure to pull the latest changes in ur branch.

**Comment by aslams2020** [comment]
@AkankshaSinghK Will u work on it?

**Comment by AkankshaSinghK** [comment]
Yes i will work on it.
But for that i need your email on which you want to receive the mail

**Comment by aslams2020** [comment]
Sure.
sayyadaslam2020@gmail.com

**Comment by AkankshaSinghK** [comment]
So tomorrow send me the mail id and i will do my work and you will get one
access key on your mail. Give me that access key to implement the
functionality.

**Comment by aslams2020** [comment]
I already sent the email id above.
Also, Which functionality will you be using ?

**Comment by aslams2020** [comment]
> I already sent the email id above. Also, Which functionality will you be using ?

Any updates @AkankshaSinghK

**Comment by aslams2020** [comment]
Closed due to no response and inactiveness
