### ISSUE TITLE
{Bug} video overflow 

### ISSUE THREAD

**Issue by Abhishek2634** [aslams2020/Stark-Tech-Portfolio#150]
@aslams2020  videos are not responsive in mobile view. Assign this issue to me under Gssoc , hacktoberfest label. thanks.
<Br/>
<img width="354" alt="Screenshot 2024-10-04 at 9 05 14 PM" src="https://github.com/user-attachments/assets/b0f47d6d-d1b4-4f5c-8bba-019692f16943">

**Comment by aslams2020** [comment]
@Abhishek2634 Sorry for the delay, you can start working on it,

**Comment by aslams2020** [comment]
@Abhishek2634 Any updates?

**Comment by aslams2020** [comment]
Closed due to inactivity and no response
