### ISSUE TITLE
Footer section

### ISSUE THREAD

**Issue by rounakdey6** [aslams2020/Stark-Tech-Portfolio#153]
There's no proper footer section , i want to add the feature , please assign this to me

**Comment by ravi-kumar2003** [comment]
I came across this issue, and I would love to help contribute to resolving it.please assign this to  me

**Comment by Priyanshi0112** [comment]
There's no proper footer section ,I would like  to add this feature .
 please assign this task  to me under GSSOC-ext!

your regards
Priyanshi Bhargava
FullStack Web Developer

**Comment by vikassahu1** [comment]
Hello, I want to work on this issue please assign me this work under label hacktoberfest.
Thank You!

**Comment by rounakdey6** [comment]
Please level this issue and assign to me

**Comment by pameladeysarkar2003** [comment]
please assign me with this task i woud like to contribute to it @aslams2020
