### ISSUE TITLE
✨[feature enhancement] : make the ui better ✨

### ISSUE THREAD

**Issue by snehaapratap** [aslams2020/Stark-Tech-Portfolio#155]
![image](https://github.com/user-attachments/assets/b32689ed-2dc9-4336-b43a-e11686b4b53c)
the ui of this page can be made better .
kindly do assign this task to me.
Thank you!

**Comment by aslams2020** [comment]
I think, Current appearances page has a better UI too.
Can you elaborate what changes are u planning to make?

**Comment by snehaapratap** [comment]
few texts arent aligned properly in the textbox, it is clearly visible in the screenshot attached above.

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @aslams2020
