### ISSUE TITLE
Improve Navbar Design and Fix Active Section on Scroll

### ISSUE THREAD

**Issue by idk-mr4tyunjay** [aslams2020/Stark-Tech-Portfolio#16]
The current navbar design requires improvements for better user experience. Additionally, the active section highlighting does not work correctly when the page is scrolled down. This needs to be fixed so that the active section is properly highlighted as the user navigates through different parts of the page.

![Screenshot 2024-10-01 193209](https://github.com/user-attachments/assets/0ce036bc-c11e-4985-b850-de0a6775cc25)

Tasks:

Redesign the navbar for better visual appeal.
Ensure that the active section is dynamically updated based on the scroll position.

@aslams2020 can you assign this issue to me

**Comment by AyutheCoder** [comment]
I can improve the navbar,please assign this task to me with label of GSSOC Ext 24 and Hacktoberfest

**Comment by Ishajain0** [comment]
PLEASE ASSIGN THIS ISSUE TO ME .I WOULD LIKE TO TRY ,TO  FIX THIS ISSUE.

**Comment by Ishajain0** [comment]
@aslams2020 PLEASE ASSIGN THIS ISSUE TO ME .I WOULD LIKE TO TRY ,TO FIX THIS ISSUE.

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @aslams2020
