### ISSUE TITLE
Adding the Facebook, Insta, Twitter options

### ISSUE THREAD

**Issue by DBasu2610** [aslams2020/Stark-Tech-Portfolio#161]
We need to enhance the footer by adding social media icons for Facebook, Twitter, and Instagram to improve user engagement and provide easy access to our social media pages. These icons should be styled consistently with the overall design of the website.

Requirements:

Add Facebook, Twitter, and Instagram icons in the footer.
Icons should be clickable and link to the respective social media pages (use placeholder links for now).
Ensure that the icons match the website's design (consistent size, color, and alignment).
Add hover effects for better user experience (e.g., color change or slight animation on hover).

**Comment by aslams2020** [comment]
Already Completed #113
