### ISSUE TITLE
Updating Hovering Effects To the Navbar

### ISSUE THREAD

**Issue by Tanushree084** [aslams2020/Stark-Tech-Portfolio#162]
Hey @aslams2020 ,

I want to update the hovering effects on the navlinks of the website
Currently, The hovering effects contains yellow shadow which is not looking consistent.

Can you please assign me this issue under gssoc extd and hactoberfest?

**Comment by aslams2020** [comment]
Go ahead. Make sure it is consistent

**Comment by pameladeysarkar2003** [comment]
please kindly assign me with this task @aslams2020 
we can hovering effect to look it more interactive

**Comment by aslams2020** [comment]
@Tanushree084 Are u working on it ?

**Comment by Tanushree084** [comment]
yes

**Comment by aslams2020** [comment]
@Tanushree084 Any updates?
