### ISSUE TITLE
Adding "follow us on socials" in Appearance.html 

### ISSUE THREAD

**Issue by nksmanya** [aslams2020/Stark-Tech-Portfolio#163]
I would like to add the Follow us on social section to the appearance.html.
Please assign this issue to me @aslams2020 

Also assign the respective level labels and hacktoberfest-accepted label to this issue.

**Comment by aslams2020** [comment]
@nksmanya Can you please add it in the "movies" page and "Watch video " page? 
(include the footer from appearance.html into the above two page too...)

**Comment by pameladeysarkar2003** [comment]
please assign me with this task @aslams2020 i would like to contribute
