### ISSUE TITLE
The contents of the Hero page does not align correctly on larger screens.

### ISSUE THREAD

**Issue by SAMluci666** [aslams2020/Stark-Tech-Portfolio#167]
### Issues
- The content of the hero page does not align correctly (in the center) on larger screens 
![image](https://github.com/user-attachments/assets/2525dc22-4d95-4a51-a44d-8f4efd8c0e04)

### Proposed Changes
- Align the items correctly.
- Make sure all other items are correctly assigned in appearance as well as movie pages.
- Add a hover effect on these buttons (shown in the picture.)

Please assign this to me under hacktoberfest, gssoc, level 2

**Comment by aslams2020** [comment]
fixed in #165
