### ISSUE TITLE
Make Button's more interactive 

### ISSUE THREAD

**Issue by Harshgupta88156** [aslams2020/Stark-Tech-Portfolio#168]
![Screenshot 2024-10-05 183750](https://github.com/user-attachments/assets/9fcf08aa-08b4-4c25-bd62-34feedfd3c38)
Whenever hovering in these buttons we change it's colour to white and more additional effects can be added such as box shadowing etc.

Please assign me this project under GSSOC extd and hacktoberfest, i will surely rectify it and make it more better!!

**Comment by aslams2020** [comment]
Make sure it is consistent and smooth.

**Comment by danishsheikh1122** [comment]
sir I want to make a contribution  , please assign me

**Comment by Akanshaku** [comment]
Please assign me this project under GSSOC extd. I will make it look more attractive .

**Comment by vikassahu1** [comment]
Hello, I want to work on this issue please assign me this work under label hacktoberfest.
Thank You!

**Comment by aslams2020** [comment]
@Harshgupta88156 The changes are already been made. 
Let me know if you want to work on it otherwise will have to close it due to timebound.

**Comment by aslams2020** [comment]
Closed due to inactivity and no response
