### ISSUE TITLE
improving the UI of the contact us page

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [aslams2020/Stark-Tech-Portfolio#169]
I want to improve the Ui of the contact us page
@aslams2020 can you please assign me this so i can work on this quickly.

<img width="809" alt="Screenshot 2024-10-05 at 6 58 21 PM" src="https://github.com/user-attachments/assets/39ecc533-de76-4031-8d0d-6c6dce0a6374">

**Comment by danishsheikh1122** [comment]
hello sir I would like to  make this ui more crazy please assign me this task

**Comment by pameladeysarkar2003** [comment]
kindly please assign me with this task i would like to contribute it @aslams2020
