### ISSUE TITLE
Feature: Section For all the technologies developed by Stark Tech

### ISSUE THREAD

**Issue by Tamanna225** [aslams2020/Stark-Tech-Portfolio#171]
Add a page named Stark Expo which will contain all the technologies developed by Stark Tech it will be exactly like Stark Expo where all the technologies ever created by Stark Tech would be shown. From the technologies discovered by Harvard Stark to the technologies discovered by Tony Stark.

**Comment by Koushik-Biswas** [comment]
Hi, I'd like to work on this issue. Please assign it to me.

**Comment by aslams2020** [comment]
Will let u know. if we want this to be in the web.

**Comment by aslams2020** [comment]
@Tamanna225 You can start working on it

Add the link to that page here - 
![image](https://github.com/user-attachments/assets/5090f6d4-8df1-4505-b410-810c42f50d2c)

**Comment by aslams2020** [comment]
Level will be assigned based on the work.

**Comment by Tamanna225** [comment]
Sure, Will start working on it

**Comment by aslams2020** [comment]
@Tamanna225 Any updates ?
