### ISSUE TITLE
updating the UI of global search bar

### ISSUE THREAD

**Issue by danishsheikh1122** [aslams2020/Stark-Tech-Portfolio#172]
<img width="364" alt="Screenshot 2024-10-05 at 9 02 33 PM" src="https://github.com/user-attachments/assets/5ae0209d-8486-4fd7-b75b-9e1b04ab4830">

I can improve the ui of the search bar , I can add an iron man icon to to search bar and many more. I ask u to assign me this task

**Comment by ChathuraHasanga44** [comment]
i like to work with this issue. can assign me for this issue.

**Comment by pameladeysarkar2003** [comment]
please assign me with this task @aslams2020 i would like to contribute to it
