### ISSUE TITLE
Searchbar is not showing results.

### ISSUE THREAD

**Issue by sayanp607** [aslams2020/Stark-Tech-Portfolio#174]
![Screenshot 2024-10-05 212244](https://github.com/user-attachments/assets/2385deae-520f-4e65-8ff1-9b6c56c67a5e)
The searchbar present here does not show any result when searching on it.Please assign this task to me, I will fix it.

**Comment by vinay7376** [comment]
I can do this, please give this work to me

**Comment by vikassahu1** [comment]
Hello, I want to work on this issue please assign me this work under label hacktoberfest.
Thank You!

**Comment by pameladeysarkar2003** [comment]
the above possible solution can be adding javascript 
kindly please assign me with thistask @aslams2020
