### ISSUE TITLE
Fix contact page CSS contact3.jpg asset route

### ISSUE THREAD

**Issue by Emilio-PdeA** [aslams2020/Stark-Tech-Portfolio#175]
Noticed that a 404 was received when requesting for `contact3.jpg`:

![Screenshot 2024-10-05 at 6 52 51 PM](https://github.com/user-attachments/assets/f2bd43f2-d947-490d-9866-f3fc2981f013)

**Cause:** Wrong asset route in CSS for contact3.jpg.

I would like to contribute to this project and participate in hacktoberfest 2024 by solving this issue.  
@aslams2020

**Comment by pameladeysarkar2003** [comment]
kindly please assign me with this task @aslams2020
