### ISSUE TITLE
changes requested for index.html

### ISSUE THREAD

**Issue by UdayVaidya** [aslams2020/Stark-Tech-Portfolio#179]
Here’s the revised summary of the changes made to the index.html file, formatted as comments for your pull request (PR) using "you should change" phrasing:

Recommendations for Changes:
1. Image Path Correction:
You should change the logo image path in the <div class="logo" id="ironmask"> from:
     <img src="assets\logo\icon.png" alt="logo" srcset="">
to:
     <img src="assets/logo/icon.png" alt="logo" srcset="">
- This change ensures that the logo image loads correctly across different browsers.
Accessibility Enhancement:
You should add an aria-label to the "Back to Top" button for improved accessibility:
     <button id="BacktoTop" aria-label="Back to top">
- This helps users relying on assistive technologies understand the button's purpose.
Code Cleanup:
You should remove the duplicate <link> for Font Awesome:
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
- This reduces redundancy and improves loading efficiency.
4. Commenting:
You should add comments in the JavaScript sections to clarify the purpose of specific functions, enhancing maintainability.
General Improvements:
You should ensure that all <script> tags are placed at the end of the body for better performance and loading times.
Testing:
You should verify that the logo image loads correctly.
You should confirm that the "Back to Top" button is accessible and functions as intended.
You should check that the overall layout and functionality remain intact after changes.

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @aslams2020

**Comment by aslams2020** [comment]
@pameladeysarkar2003 Please don't spam on every issue.
The issue assignments are on first come first serve basis...so please don't add comment on each issues in the repo..
As I have seen u adding comments in more than 15 issues so far

Please find some issues by yourself too.
Hope u understand
