### ISSUE TITLE
adding functionality to submit button in contact us

### ISSUE THREAD

**Issue by bhavanireddy57** [aslams2020/Stark-Tech-Portfolio#18]
I would like to add a functionality to the submit button after entering details so that it enhances the contact us feature. I want to work on this update so,please assign it to me

**Comment by shraddhabaghel** [comment]
i would like to add functionality to this. please assign it to me

**Comment by aslams2020** [comment]
@bhavanireddy57 Assigned to you

**Comment by pameladeysarkar2003** [comment]
please assign mw with the task @aslams2020

**Comment by aslams2020** [comment]
@pameladeysarkar2003 please stop doing scams. I'm requesting you from last 40 mins.
