### ISSUE TITLE
style.css

### ISSUE THREAD

**Issue by UdayVaidya** [aslams2020/Stark-Tech-Portfolio#181]
Recommendations for Changes:
1. Scrollbar Styling:
-You should add custom styling for the vertical scrollbar to enhance the user experience:
-This change improves the visual appeal of the scrollbar.

2. Progress Bar Styling:
You should ensure the progress bar has a visually appealing gradient and shadow:

3. Animation Enhancements:
You should define keyframes for animations to create smooth transitions:

4. Navbar and Background Styling:
You should ensure the navbar is fixed and styled appropriately:
 
5. Movie Card Styling:
You should enhance the styling of movie cards for better visual appeal:

6. Back to Top Button Styling:
You should ensure the "Back to Top" button is styled for visibility and interaction:
   

Testing:
You should verify that all styles render correctly across different devices and screen sizes.
You should ensure that hover effects and animations function as intended.

**Comment by vikassahu1** [comment]
Hello, I want to work on this issue please assign me this work under label hacktoberfest.
Thank You!

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @aslams2020

**Comment by aslams2020** [comment]
@UdayVaidya Website is updated.
