### ISSUE TITLE
Documentation needs a little work

### ISSUE THREAD

**Issue by dhruvveragiwala** [aslams2020/Stark-Tech-Portfolio#184]
The Documentation should include the features of the website. They are not mentioned properly. I would like to edit it and make more user freindly.

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @aslams2020

**Comment by aslams2020** [comment]
@dhruvveragiwala Make sure to add relevant information.

**Comment by aslams2020** [comment]
Hi, My Account got recovered, You can start working on the Issue. 
Sorry for the inconvience. Keep Contributing 🚀
