### ISSUE TITLE
Social icons gets hidden on hovering

### ISSUE THREAD

**Issue by saadgibawa** [aslams2020/Stark-Tech-Portfolio#188]
Hii! @aslams2020 
The custom circular cursor effect hides the social media icons when hovering over them making it difficult for users to see or interact with them effectively. Please assign me this issue

https://github.com/user-attachments/assets/fce9db7a-3de3-4fde-929c-63b738301903

**Comment by vikassahu1** [comment]
Hello, I want to work on this issue please assign me this work under label hacktoberfest.
Thank You!

**Comment by aslams2020** [comment]
the footer has been updated along with the social icons.
you can still find and raise new issues.

**Comment by saadgibawa** [comment]
@aslams2020 But in the appearances section the previous footer is still in use. I have a suggestion that the footer across all the other pages of the website should be added to maintain the overall consistency of the website

**Comment by aslams2020** [comment]
@saadgibawa Hi, Actually, someone is already assigned to implement the same footer as the home page in all other pages footer. Hence I had to close this one. 
Hope you understand.

**Comment by saadgibawa** [comment]
@aslams2020 Sure! No issues
