### ISSUE TITLE
in appearances page, i want to create a slider box 

### ISSUE THREAD

**Issue by anish013326** [aslams2020/Stark-Tech-Portfolio#189]
#### in appearances page, i want to create a slider box  to make navigation of all movies easier through NEXT and PREVIOUS button 
![image](https://github.com/user-attachments/assets/acccfa35-f2c5-4d64-a8f3-db67b391b840)

like back  to introduction as back to previous movies and forward to installation as next movies

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @aslams2020
