### ISSUE TITLE
Margin on Submit button 

### ISSUE THREAD

**Issue by rohir1132yadav** [aslams2020/Stark-Tech-Portfolio#19]
i want to set the Submit button has margin bottom 
and there is gap between submit botton and down side become white

**Comment by monishkumardvs** [comment]
i want to work in this project can u assign me

**Comment by aslams2020** [comment]
@rohir1132yadav Assigned to you

**Comment by rohir1132yadav** [comment]
please add these tag on my PR   enhancement
<https://github.com/Trisha-tech/OnlineBookSales/labels/enhancement> level1
<https://github.com/Trisha-tech/OnlineBookSales/labels/level1> gssoc-ext
<https://github.com/Trisha-tech/OnlineBookSales/labels/gssoc-ext>
hacktoberfest
<https://github.com/Trisha-tech/OnlineBookSales/labels/hacktoberfest>

**Comment by rohir1132yadav** [comment]
please add it
