### ISSUE TITLE
adding animation in the socialmedia icons in footer

### ISSUE THREAD

**Issue by ritikm31** [aslams2020/Stark-Tech-Portfolio#194]
want to add animation in the all social media icons in the footer

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @aslams2020

**Comment by aslams2020** [comment]
Hi @ritikm31 You can start working on it. 
I got my account back today. Sorry for the inconvinience.

**Comment by ritikm31** [comment]
Ok I'll gonna work on it
