### ISSUE TITLE
[Bug] small pic appearance in menu

### ISSUE THREAD

**Issue by vedant3337** [aslams2020/Stark-Tech-Portfolio#199]
Still after someone fix this issue for other pages in appearance page small logo is there. 

Also too less padding given in search button

![SmartSelect_20241006_112249_Chrome](https://github.com/user-attachments/assets/3c1fea3a-d602-4a03-b64d-df9dc543dfad)

**Please assign me this issue and label gssoc-ext, hacktoberfest**

**Comment by pameladeysarkar2003** [comment]
please assign me with this task @aslams2020

**Comment by aslams2020** [comment]
Hi @vedant3337  You can start working on it. 
I got my account back today. Sorry for the inconvinience.
