### ISSUE TITLE
Implement Feedback form for website

### ISSUE THREAD

**Issue by Codewithmeowmeow** [aslams2020/Stark-Tech-Portfolio#202]
hey @aslams2020  your website is really fascinating.
I would like to contribute to this website by adding rate us feature where users can rate your website by giving 5,4,3,2,,1 star as per their like and a mini comment box where they can comment also.
KINDLY ASSIGN IT TO ME AND ADD REQUIRED LABELS.

**Comment by aslams2020** [comment]
Did you mean the Feedback form ?

**Comment by Codewithmeowmeow** [comment]
> Did you mean the Feedback form ?

Yes

**Comment by aslams2020** [comment]
Ok proceed.
Add the link to feedback form in the footer , by replacing "Contact" with "Give Feedback"

![image](https://github.com/user-attachments/assets/30a77bdd-f1d6-4a5c-a380-1db7f4055353)

**Comment by aslams2020** [comment]
Level will given based on the work.

**Comment by Codewithmeowmeow** [comment]
> Ok proceed. Add the link to feedback form in the footer , by replacing "Contact" with "Give Feedback"
> 
> ![image](https://private-user-images.githubusercontent.com/131389695/373963744-30a77bdd-f1d6-4a5c-a380-1db7f4055353.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMzg0MDcsIm5iZiI6MTcyODIzODEwNywicGF0aCI6Ii8xMzEzODk2OTUvMzczOTYzNzQ0LTMwYTc3YmRkLWYxZDYtNGE1Yy1hMzgwLTFkYjdmNDA1NTM1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQxODA4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGVjOTVhMGE3NTM0NzM3YTg2ZDFjNDhjYjkzNjVmZmVmYzVkYTA2NzdkODYwNDU4OGU3OTVmODNhMDlhNTA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.25AroAT53pzzmGdj4otRSG35Ku7C6aLn-mAyVwxT66Y)


https://github.com/user-attachments/assets/77ed706c-d407-4232-a1ca-60b3c126ae1d

is this okay? or should i enhance it more.. tell me your views how i should proceed now.

**Comment by aslams2020** [comment]
@Codewithmeowmeow It is good. But as i said, Please make a separate page for feedback form and add the link to it in the footer by replacing the "contact" with "give feedback"

**Comment by aslams2020** [comment]
We can't merge the changes as above coz, we dont want to disturb the Homepage.

You can ask me if any doubt.

**Comment by Codewithmeowmeow** [comment]
> We can't merge the changes as above coz, we dont want to disturb the Homepage.
> 
> You can ask me if any doubt.


https://github.com/user-attachments/assets/cd6b992a-29b0-4bd9-8bf1-c8406bd2af7f

**Comment by aslams2020** [comment]
You can Make the PR. Will review it.

**Comment by aslams2020** [comment]
Hi @Codewithmeowmeow, u can start working on it. As your PR doesn't seem to have any changes, i request you to make a new PR with the changes in 

I got my account back today. Sorry for the inconvinience.

**Comment by aslams2020** [comment]
@Codewithmeowmeow Will you work on it?
