### ISSUE TITLE
Hover Animation

### ISSUE THREAD

**Issue by akhil11sharma** [aslams2020/Stark-Tech-Portfolio#205]
I want to add some hover animation to the webpage kindly provide me the acess

**Comment by aslams2020** [comment]
@akhil11sharma Can you elaborate more

**Comment by akhil11sharma** [comment]
<img width="1800" alt="Screenshot 2024-10-06 at 9 54 05 PM" src="https://github.com/user-attachments/assets/7ac23bfd-6830-4b4f-8b3c-59ffc5a24f9b">
The red background creates a high contrast, making the images less noticeable. However, I can implement a hover effect on the images to make them stand out when the mouse moves over them. This approach will enhance the user experience, making it easier for users to distinguish and interact with the images more effectively.Kindly grant me acess to showcase my work

**Comment by aslams2020** [comment]
@akhil11sharma Go ahead.

**Comment by aslams2020** [comment]
Hi @akhil11sharma  You can start working on it now. 
I got my account back today. Sorry for the inconvinience.

**Comment by aslams2020** [comment]
@akhil11sharma Will wait until tomorrow.
Please do let me know if any updates.
