### ISSUE TITLE
Adding Login and Signup Page

### ISSUE THREAD

**Issue by subin-shk** [aslams2020/Stark-Tech-Portfolio#208]
Addition of Login and Signup Page allows user to login to their account. Addition of these features also allows users to bookmark Tony Stark's movies and leave a comment.

Please assign this task to me

**Comment by shaina123786** [comment]
I would like to work on this. plz assign to me.

**Comment by aslams2020** [comment]
@subin-shk We currently, don't need that feature to be implemented. 
You can still find and raise new issue
