### ISSUE TITLE
adding footer section to the comic-section

### ISSUE THREAD

**Issue by Slambot01** [aslams2020/Stark-Tech-Portfolio#211]
I would like to work on this issue

**Comment by aslams2020** [comment]
Will assign the level based on the work.

**Comment by Slambot01** [comment]
ok

**Comment by aslams2020** [comment]
> @Slambot01 Please add the footer section in the homepage to following pages - `Appearances`, `Comics`, `WatchVideo`, `Movies` and `Variants` page. (make sure to change only respective .css files of the above pages.)

Hi @Slambot01  You can start working on it. 
I got my account back today. Sorry for the inconvinience.

**Comment by aslams2020** [comment]
@Slambot01 Are u working on it? Let me know asap.

**Comment by Slambot01** [comment]
Yes,I'll generate pr today for it

**Comment by aslams2020** [comment]
Yeah, please pull the latest changes first in ur branch.
Thanks!

**Comment by Slambot01** [comment]
@aslams2020        please assign the level to the PR

**Comment by aslams2020** [comment]
> @aslams2020 please assign the level to the PR

I already assigned it level3. please check

**Comment by Slambot01** [comment]
thank you.
