### ISSUE TITLE
 Add Hover and Color to Social Icons

### ISSUE THREAD

**Issue by Shekhar-Raj** [aslams2020/Stark-Tech-Portfolio#217]
<h2>I want to add a hover effect to the social icons, so whenever i hover to icon the size of icon increases and each icon changes their color to basic:</h2>

<h3>Here:</h3>

![image](https://github.com/user-attachments/assets/df653f29-4966-48f3-9f8e-bb50b253d4ec)

<h3>Demo</h3>

https://github.com/user-attachments/assets/e99bbe48-6091-4bf6-9d1b-b6e9b12a8d1f

**Comment by aslams2020** [comment]
#194 is working on it

**Comment by Shekhar-Raj** [comment]
> #194 is working on it

ao are you closing this issue ?

**Comment by aslams2020** [comment]
Yeah
