### ISSUE TITLE
Comics section is not opening when accessed through appearances section

### ISSUE THREAD

**Issue by saadgibawa** [aslams2020/Stark-Tech-Portfolio#218]
There's a small issue that when trying to access the comics section  from appearances section then anything doesnt happen and it is not responding otherwise it is working fine. Please assign me this issue

**Comment by aslams2020** [comment]
Please make the below changes - 
1. From Appearances section, Comics section should be accessible 
2. The logo in the navbar of appearances should have same size as there in other pages.
3. From Movies section, Comics section should be accessible

**Comment by aslams2020** [comment]
as the issue you raised was not sufficient to be given a level1.
I extended some more tasks to it.

**Comment by saadgibawa** [comment]
@aslams2020 Sure. Thanks!

**Comment by aslams2020** [comment]
@saadgibawa Hi, My Account got recovered, You can start working on the Issue. 
Sorry for the inconvience. Keep Contributing 🚀
