### ISSUE TITLE
Add login and signup 

### ISSUE THREAD

**Issue by shraddhabaghel** [aslams2020/Stark-Tech-Portfolio#22]
I have added the login and signup button in nav bar to make the page look more user friendly and user interactive.
![login signup](https://github.com/user-attachments/assets/743ce13e-79c9-4f16-908d-2dfa08947acf)
I hope @aslams2020 you like your website to be more user friendly so assign me this issue so that i can further work on it

**Comment by SHREYA-2k5** [comment]
can you assign me this issue. i have worked on this before and i am a beginner.

**Comment by aslams2020** [comment]
We currently don't need that feature to be implemented.
You can still find and raise new issues.
