### ISSUE TITLE
Bug - Twitter icon

### ISSUE THREAD

**Issue by poorvikaa08** [aslams2020/Stark-Tech-Portfolio#220]
The current display button for Twitter on the website still shows the old Twitter bird icon on the appearances page.
Twitter has rebranded to "X" with a new logo, so this button should be updated to reflect the latest branding.

Screenshot 📸 
![image](https://github.com/user-attachments/assets/34fb681f-8ac0-4c43-b2d9-e88b38c1353c)

@aslams2020 
I would like to work on this issue under gssoc-ext and hactoberfest

**Comment by aslams2020** [comment]
@poorvikaa08 Currently someone is working on the footer. Once it get's done will assign u

**Comment by poorvikaa08** [comment]
@aslams2020 Sure, let me know when it gets updated. Thank you 😊

**Comment by aslams2020** [comment]
@poorvikaa08 Sorry for the inconvience. In the homepage the new X icon is already there - 
![image](https://github.com/user-attachments/assets/1dd252ca-4744-4219-814f-6a9f6982316d)


And The one who is working on the footer, will be including the same footer from homepage to other absent pages. 
Atfirst i thought it's old icon but now i saw that its the updated one.

Hope you understand.
