### ISSUE TITLE
Bug - Iron man logo/icon

### ISSUE THREAD

**Issue by poorvikaa08** [aslams2020/Stark-Tech-Portfolio#221]
On the appearances page, there's a missing Iron Man logo/icon in the header section
(Top left position)

![image](https://github.com/user-attachments/assets/0b52182c-944e-4ae0-9301-b0d9dc2d7c2d)

I will fix this.
@aslams2020 could u assign it to me?

**Comment by aslams2020** [comment]
#218  is working on it.
