### ISSUE TITLE
Favicon Not Visible in Browser Tab or Search Bar..

### ISSUE THREAD

**Issue by piyush9420707813** [aslams2020/Stark-Tech-Portfolio#222]
https://github.com/user-attachments/assets/34185dc0-d8e7-425f-bd47-b590d7d23918

**Comment by piyush9420707813** [comment]
yess

**Comment by piyush9420707813** [comment]
please assign me with the task @aslams2020

**Comment by piyush9420707813** [comment]
i want to add ironman face there

**Comment by aslams2020** [comment]
@piyush9420707813 Add favicons in those pages, wherever it is absent.

**Comment by aslams2020** [comment]
@piyush9420707813 it is a minor issue to get you started. it's been 3days.
let me know until tomorrow or i have to close the issue due to time took to complete

**Comment by aslams2020** [comment]
Closed due to inactivity and no response
