### ISSUE TITLE
#can add one more section descreption regarding his awards/achievements/remarkable-things

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [aslams2020/Stark-Tech-Portfolio#227]
add a descriptive section showcasing his awards/achievements/remarkable-things

**Comment by aslams2020** [comment]
Are you willing to add a section in the homepage or a separate page for it?

**Comment by SanikaBhalerao1345** [comment]
In the home page itself.
Is that ok? @aslams2020

**Comment by aslams2020** [comment]
I want you to create a separate page for it and add the link to in the footer 
(Replace the below highlighted link with "Remarkable-Things" and link the page there.
![image](https://github.com/user-attachments/assets/5ab8d2bc-837a-4e4d-9b17-b413d5fe37fd)

Let me know, if that works for you.

**Comment by SanikaBhalerao1345** [comment]
ok sure i will do it

**Comment by aslams2020** [comment]
@SanikaBhalerao1345 Good. Assigning you. Make sure to follow the website theme

Level will be assigned based on the Work. go ahead

**Comment by SanikaBhalerao1345** [comment]
@aslams2020 pls check i have raised a pr
