### ISSUE TITLE
Adding a custom preloader

### ISSUE THREAD

**Issue by Peart-Guy** [aslams2020/Stark-Tech-Portfolio#229]
@aslams2020 
I want to add a customized preloader to you webapp which will match the theme and aesthetic of the site.

This is a basic sample to showcase what I can offer. The final product may vary depending on your specific needs and preferences. I look forward to the opportunity to contribute to your project .

https://github.com/user-attachments/assets/e5db73da-2e6b-4639-b8c1-8c74d21c75e8

**Comment by aslams2020** [comment]
#180 is working on it

**Comment by aslams2020** [comment]
@Peart-Guy You can start working on it. 
But please let me know which pre-loader are u willing to add.

**Comment by aslams2020** [comment]
Level will be assigned based on the work.
