### ISSUE TITLE
Responsive Layout Enhancement for Contact Form

### ISSUE THREAD

**Issue by arcane-2004** [aslams2020/Stark-Tech-Portfolio#23]
**Issue Description:**
The contact form's layout is not fully optimized for different screen sizes, particularly for mobile devices. Currently, the form fields and buttons appear cramped and may not provide the best user experience on smaller screens. To improve responsiveness, adjustments to spacing, alignment, and font scaling are needed.

![{8776A308-9211-4C84-9715-CB72BA3A3F53}](https://github.com/user-attachments/assets/9edfcf11-f237-43eb-8e60-9df390bc0488)

**Comment by arcane-2004** [comment]
Please assign it to me. I am currently working on this.
Also please add tag like gssoc-ext, level and so on.

**Comment by aslams2020** [comment]
@arcane-2004 Good one.
Will Assign you after the other contributor is done with the designing part.
You can start after i assign u
