### ISSUE TITLE
Animation on scroll on comics page 

### ISSUE THREAD

**Issue by Priyanshi0112** [aslams2020/Stark-Tech-Portfolio#230]
Implementing scroll animations in the comic section of the website will enhance user engagement and create a more dynamic viewing experience. As users scroll down the page, comic panels or elements will animate into view, capturing attention and adding a layer of interactivity.

Benefits :

1.  Enhanced User Engagement: Captures attention and encourages users to explore content more thoroughly.
2.  Improved Visual Appeal: Transforms static content into a lively experience, making it more attractive.
3.  Increased Interactivity: Creates a sense of connection, enhancing emotional responses to the comics.
4.  Clearer Storytelling: Guides users through the narrative, emphasizing key moments and transitions.
5.  Modern Aesthetic: Aligns with contemporary web design trends, improving user perception.
6.  Encouragement to Share: Visually engaging content is more likely to be shared, increasing traffic and visibility.

**Comment by aslams2020** [comment]
Level will be assigned based on the work. Go ahead
