### ISSUE TITLE
the  variants page  dosen't have the scroll to up button 

### ISSUE THREAD

**Issue by 2004pra** [aslams2020/Stark-Tech-Portfolio#231]
please assign me this issue under gssoc extd 24 , hactober fest , and make it level 2 if you can please ..
this is the page sir 
![Screenshot 2024-10-26 003619](https://github.com/user-attachments/assets/9a93e995-102c-42c1-8a06-ca90ff7e774a)
it will be amazing to contribute to your project as i am also a fan of tony stark.....

**Comment by 2004pra** [comment]
when will you assign the level later on pr  please make it level 2

**Comment by aslams2020** [comment]
As it is a minor issue to resolve. Level1 is sufficient for it.
Go ahead

**Comment by 2004pra** [comment]
aslam bhai close karna bhul gaye issue pr toh kab ki merge ho gayi @aslams2020

**Comment by aslams2020** [comment]
Okay! tumne issue no. mention ni kiya tha :(
