### ISSUE TITLE
Creating Privacy policy and Terms & Conditions page

### ISSUE THREAD

**Issue by VidhanThakur09** [aslams2020/Stark-Tech-Portfolio#232]
### Description 

To ensure user privacy and transparency, it's essential to establish comprehensive Privacy Policy and Terms & Conditions pages. These pages will outline all the necessary policies and terms. Additionally, they will clearly define the user's rights and responsibilities when interacting with the project.

@aslams2020  can you assign this issue to me with labels "gssoc-ext" with levels and "hacktoberfest-accepted";

**Comment by aslams2020** [comment]
@VidhanThakur09 Go ahead. 
Make sure to follow the website theme and add include Navbar and footer.

**Comment by aslams2020** [comment]
Level will be assigned based on the work.

**Comment by VidhanThakur09** [comment]
Sure, I'll get started on it.
