### ISSUE TITLE
Fix LOGO's size for responsiveness and Add a favicon

### ISSUE THREAD

**Issue by SurajSG23** [aslams2020/Stark-Tech-Portfolio#234]
Hey, In the appearances section the stark logo is not visible once the size (width) is reduced.
And also i would like to add the same logo to the favicon. 

![image](https://github.com/user-attachments/assets/d810e822-c58d-4d0c-b6f7-f879dbf9ba7e)

Please assign me this under gssoc-ext and hacktoberfest. Thank You!

**Comment by aslams2020** [comment]
Fixed in #243
