### ISSUE TITLE
Adding the merices table

### ISSUE THREAD

**Issue by Aman-G-upta** [aslams2020/Stark-Tech-Portfolio#238]
Adding the merices table to the readme file
@aslams2020 , please assign me under this issue !!!
![image](https://github.com/user-attachments/assets/bc70630d-cdd9-4b35-b779-48a09c5be6bf)

**Comment by aslams2020** [comment]
As this is a documentation issue i am adding extra task  - 
Make this changes in the readme file -  
1. Add featured In GSSOC Extended Program 2024 
2. Add the Table as given in the image above containing repo info

![WhatsApp Image 2024-10-18 at 16 44 29_461ef25a](https://github.com/user-attachments/assets/8922d1ca-488c-4f27-8653-638ab078a9a0)
![WhatsApp Image 2024-10-18 at 16 45 13_095c067f](https://github.com/user-attachments/assets/5ca5e503-b656-40a1-ae31-e5cf82e952fb)

3. You can add a contributors images.
 ![WhatsApp Image 2024-10-18 at 17 03 24_a8d07159](https://github.com/user-attachments/assets/16eb739d-7ec6-4bd9-8b1c-10ddc53dfc40)
