### ISSUE TITLE
 Issue Title: Improve Navbar Design with Enhanced Visuals and Responsiveness

### ISSUE THREAD

**Issue by Piyush01-672** [aslams2020/Stark-Tech-Portfolio#239]
The current navbar could be improved to enhance user experience and aesthetics. Proposed improvements include:

1. Add White Border: Introduce a white border around the navbar with rounded corners to make it stand out.
2. Hover Effects: Enhance link hover effects with subtle animations.
3. Responsive Adjustments: Make the navbar more user-friendly on mobile by adjusting padding and alignment in the responsive layout.
4. Font Size: Adjust font size for better readability.

**Comment by aslams2020** [comment]
currently we dont need to implement those.
thankyou. You can still find and raise new issue.
