### ISSUE TITLE
Feature: Create a Tony Stark Appearances Page with Famous Dialogues

### ISSUE THREAD

**Issue by Tamanna225** [aslams2020/Stark-Tech-Portfolio#24]
I would like to add a new page to the Stark Tech Portfolio that features a chronological list of Tony Stark's appearances in Marvel movies along with his most famous dialogues. 

This page will contain the chronological list of movies featuring tony stark no matter as guest appearance or main character and with each movie there will be mention of the famous dialogue of iron man from that movie.

Could you assign me this issue with gssoc extd 24, level and hacktoberfest labels please.

**Comment by aslams2020** [comment]
@Tamanna225 Great.
Please Add that page link in the navbar. (Follow the website's color theme) 

Page name : "Appearances"
![image](https://github.com/user-attachments/assets/8a8fe0a3-33ea-4d51-8a58-4d001c7335c5)

**Comment by aslams2020** [comment]
Ask me if any doubts.

**Comment by aslams2020** [comment]
@Tamanna225 Any updates?

**Comment by Tamanna225** [comment]
@aslams2020  Yuup working on it taking time to make it responsive... Will surely raise the PR by today evening
