### ISSUE TITLE
UI: fix the ouline of the form

### ISSUE THREAD

**Issue by AE-Hertz** [aslams2020/Stark-Tech-Portfolio#240]
fix the outline of the form as this does not look good and is not matching the theme.
![Screenshot 2024-10-26 123607](https://github.com/user-attachments/assets/987c4f47-4876-43ed-af73-0717ae6a7545)

assign me this under hacktoberfest and gssoc-ext level

**Comment by aslams2020** [comment]
Assigned to #237

**Comment by AE-Hertz** [comment]
@aslams2020 hey, i dont think it was duplicate because the @237 issue does not specify what he will be performing. well , thank you for having me.

**Comment by aslams2020** [comment]
The modification will include all the fields and form updation..That is why i had to close the issue.
hope u understand.
