### ISSUE TITLE
feat: add a contributers page .

### ISSUE THREAD

**Issue by AE-Hertz** [aslams2020/Stark-Tech-Portfolio#241]
add a contributer page for all the devs know spend their time building that.
![Screenshot 2024-10-26 123800](https://github.com/user-attachments/assets/c3310777-8bdf-476a-b6af-7abd114a4222)

assign me this under hacktoberfest and gssoc-ext, i expect level 3 for this, thank you

**Comment by aslams2020** [comment]
Add the link to contributors page in the Footer > About Us > (Replace "Press" with "Our Contributors")

**Comment by aslams2020** [comment]
Make sure to follow website theme! Will assign the level  based on the work. Go ahead

**Comment by AE-Hertz** [comment]
@aslams2020 ok, i will send PR as soon as possible . thank you.

**Comment by AE-Hertz** [comment]
@aslams2020 hey i requested a PR please review, and i tried to make it aesthetic while having same theme.
