### ISSUE TITLE
Add mini chatbot to the website

### ISSUE THREAD

**Issue by rutikakengal** [aslams2020/Stark-Tech-Portfolio#242]
This chatbot is built using Api  Key and aswers every questions which related to iron man or any other general questions like chatgpt , Assign me @aslams2020 I like to work on it , Add gssoc-ext , hactoberfest-accepted and level to this issue

**Comment by aslams2020** [comment]
Hi @rutikakengal, in the website we don't need the addition of chatbot

you can still find and raise new issues. thankyou
