### ISSUE TITLE
Creation of FAQs part

### ISSUE THREAD

**Issue by Mahy-31** [aslams2020/Stark-Tech-Portfolio#244]
The FAQs link traverses to the home page itself. So, I would like to create a FAQ part below the About part itself. Could you please assign me this task?

**Comment by aslams2020** [comment]
Can you make a new FAQ page instead ? 
Can add the link to faq here - 
![image](https://github.com/user-attachments/assets/01ef85c2-52ba-4dae-9f0a-e6fbb41fa671)

**Comment by aslams2020** [comment]
Will assign the level based on the work. Make sure to follow website theme
Go ahead!

**Comment by SumitSahu44** [comment]
assign this to me i will do it ASAP as consider to the following this or if the design and work is good so can you assign level 3 (optional)

**Comment by Mahy-31** [comment]
> Will assign the level based on the work. Make sure to follow website theme Go ahead!

Yes sure

**Comment by Mahy-31** [comment]
> Will assign the level based on the work. Make sure to follow website theme Go ahead!

And can you send me the list of questions and answers that you need me to attach in the link?

**Comment by aslams2020** [comment]
@Mahy-31 You can add whichever suits the concept and theme of the website.

**Comment by Mahy-31** [comment]
> @Mahy-31 You can add whichever suits the concept and theme of the website.

Okey

**Comment by aslams2020** [comment]
@Mahy-31 any updates?

**Comment by Mahy-31** [comment]
> @Mahy-31 any updates?

I'm currently working on the questions. I'm not sure what could be the questions. So I'm analysing the website so that I can get any idea. If you get any questions on your mind please let me know.

**Comment by Mahy-31** [comment]
> Add 5-6 questions. anything you think that can be added

Ok. Will update you about it by tomorrow.

**Comment by aslams2020** [comment]
@Mahy-31 Please a make a PR.
This issue maybe assigned to other contributors. Will wait till tomorrow

**Comment by aslams2020** [comment]
@Mahy-31 Will assign someone else, due to no response.
