### ISSUE TITLE
Hover animation on Footer social logos

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [aslams2020/Stark-Tech-Portfolio#249]
I want to add hover animation on the footer social icons so that they change color on hover, respective to the websites
Twitter changes to black
Facebook to blue
Instagram to the orange-reddish color of the official logo, etc

![image](https://github.com/user-attachments/assets/5c6edb61-271a-467d-b785-7381e4878985)

I would like to work on the issue. I will update you about the work progress and share with you to know your feedback along the way.

I wanted to work on adding the Footers on the missing pages but noticed you had assigned it to someone 3 weeks ago and it is still open so I cannot open that. I will add the hover animation to the home page currently and to the rest when that person has added the footer to the other pages.

**Comment by aslams2020** [comment]
#236 Completed.
