### ISSUE TITLE
Implementation of Blog Page

### ISSUE THREAD

**Issue by Shariq2003** [aslams2020/Stark-Tech-Portfolio#255]
I want to implement the Blog Page.

https://github.com/user-attachments/assets/b0f05a88-ce1e-4cdf-974e-c092f12950c2

**Comment by aslams2020** [comment]
Make sure to follow the website theme.

**Comment by Shariq2003** [comment]
> Make sure to follow the website theme.

Okay sir

**Comment by praneethaBrindavanam** [comment]
please assign this issue
