### ISSUE TITLE
Privacy Policy Link in Footer Not Redirecting

### ISSUE THREAD

**Issue by snehhhcodes** [aslams2020/Stark-Tech-Portfolio#264]
The privacy policy link in the footer is not functioning correctly, failing to redirect users to the intended privacy policy page. This issue hinders users' access to important information regarding data usage and privacy practices, which could lead to confusion and mistrust. Ensuring that this link works properly is essential for compliance and maintaining user confidence in the website.

[screen-capture (2).webm](https://github.com/user-attachments/assets/28a6ac7d-71e2-4272-a7f6-0acd46c3728e)

**Comment by snehhhcodes** [comment]
@aslams2020 please review this issue once and if suitable assign it to me

**Comment by aslams2020** [comment]
Resolved #232
