### ISSUE TITLE
The Footer can be much Better

### ISSUE THREAD

**Issue by sachinggsingh** [aslams2020/Stark-Tech-Portfolio#265]
![Screenshot 2024-10-27 123634](https://github.com/user-attachments/assets/b9b555bd-5de7-4147-be9a-6029d049907a)

I will be adding more gaps and margin to the footer so that is look independent from the @ copyright section and will add glassmorphism to the footer so that it will be looking more good 

![Screenshot 2024-10-27 123713](https://github.com/user-attachments/assets/0ca7cef1-c234-4cd1-bd99-2eace5fff8fe)

And as you can see that the cursor hide the image of the social  media icon so will be correcting that too.

**Comment by sachinggsingh** [comment]
Assign this Issue to me

**Comment by aslams2020** [comment]
The footer has been updated in all the pages same as the homepage.
