### ISSUE TITLE
Add chatbot 

### ISSUE THREAD

**Issue by shivenyadavs** [aslams2020/Stark-Tech-Portfolio#269]
Adding a chatbot to the Stark Tech Portfolio will provide an interactive and futuristic element that mirrors Tony Stark’s high-tech world, similar to J.A.R.V.I.S. The chatbot can assist users in navigating the portfolio, answering questions about your projects, skills, and experiences, and enhancing user engagement.

Proposed Solution

Create a chatbot that acts like a virtual assistant, guiding users through the portfolio and answering common questions.
The chatbot can have predefined responses for queries about your skills, showcased projects, experience, and contact details.
It should be styled with a sleek, high-tech design that fits the Stark-inspired theme, using interactive UI elements such as chat bubbles and a dark mode aesthetic.
Utilize JavaScript for chatbot interactivity, with optional integration of AI-based responses using simple APIs (for future enhancements).
Alternatives Considered

A simple FAQ section or search bar instead of a chatbot, though this would lack the interactive and futuristic appeal of a chatbot feature.

**Comment by aslams2020** [comment]
Hi, In our website context we dont need the chatbot here.
hope you understand!
