### ISSUE TITLE
Add a Visitor count

### ISSUE THREAD

**Issue by Peart-Guy** [aslams2020/Stark-Tech-Portfolio#271]
I want to add a visitor count to your  website

@aslams2020 Please assign me this issue

![Screenshot 2024-10-26 004024](https://github.com/user-attachments/assets/7723e89f-0ab4-4415-80b9-a80ef29fd146)
![Screenshot 2024-10-26 004029](https://github.com/user-attachments/assets/95edd5ab-cb85-4e44-b811-0efaa02ecdea)

**Comment by aslams2020** [comment]
![image](https://github.com/user-attachments/assets/7b31b54c-de19-4921-b50e-e049a12e8521)
Add it like this in website theme color.

![image](https://github.com/user-attachments/assets/b4718298-25b6-40db-b818-204b5ba763bb)

**Comment by aslams2020** [comment]
level will be assigned based on the work.

**Comment by praneethaBrindavanam** [comment]
please assign this  issue!!!!!!!!!!!

**Comment by aslams2020** [comment]
@praneethaBrindavanam Already assigned to @Peart-Guy. 
Please find and raise new issues.
