### ISSUE TITLE
[Feature]: Adding a Login and SignUP page

### ISSUE THREAD

**Issue by priyachau12** [aslams2020/Stark-Tech-Portfolio#274]
### Feature Request: Adding a Login and Signup Page

**Description**:  
This feature involves adding dedicated Login and Signup pages to the project to improve user experience and make the interface more organized. These pages will allow users to register and log in to the platform, providing a personalized experience once they access their account.

**Requirements**:
- **Login Page**: A clean and user-friendly page where existing users can enter their email and password to log in.
  - Fields for **email** and **password**.
  - "Forgot Password" link for users to reset their password.
  - "Sign Up" link to direct new users to the Signup page.
  - Basic input validation (e.g., required fields).

- **Signup Page**: A simple page for new users to create an account on the platform.
  - Fields for **email**, **password**, and **confirm password**.
  - "Already have an account?" link to navigate to the Login page.
  - Input validation for fields, including password match.

- **UI Design**:
  - Both pages will have a consistent design theme with the rest of the platform.
  - Responsive layout to ensure usability on different screen sizes.
  - Minimalistic and easy-to-read typography, form labels, and buttons.

**Purpose**:
- These pages provide a foundation for account-based interactions, making it easier to integrate additional features like profile settings, user preferences, and dashboard access in the future.

**Implementation**:
- Create separate HTML files (or components, if using a framework like React) for each page.
- Use CSS for styling to ensure a consistent look and feel.
- Add client-side JavaScript for basic form validation.

**Comment by aslams2020** [comment]
Hi, according to the theme and context of the website, we dont want to implement this feature.
you can still contribute to new issues.
