### ISSUE TITLE
making more attractive Home section.

### ISSUE THREAD

**Issue by SoumyaU25** [aslams2020/Stark-Tech-Portfolio#28]
I want to make the home section look more attractive and add some advance CSS features to it to make it look well responsive .
Please assign me this issue under gssoc-ext label.

**Comment by AyutheCoder** [comment]
I can make home section more interactive and attracful,please assign this task to me with label of GSSOC Ext 24 and hactoberfest

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @aslams2020

**Comment by aslams2020** [comment]
It already updated. 
You can still find and raise new issues
