### ISSUE TITLE
Logo of website in Navbar  Visibility Issue on Mobile – Enhance Responsiveness

### ISSUE THREAD

**Issue by Ankul8471** [aslams2020/Stark-Tech-Portfolio#280]
The website logo is not visible in the navbar on mobile devices due to a lack of responsiveness. This affects brand identity and user navigation, as the logo is a key visual anchor for visitors. Adjusting the navbar layout for mobile screens will ensure that the logo is prominently displayed, creating a cohesive and professional look across all devices. This improvement will enhance user experience and reinforce brand recognition, especially for mobile users.

![Screenshot 2024-10-27 234334](https://github.com/user-attachments/assets/2d16e134-b4e1-4f52-aa50-236e5877b2dd)

**Comment by aslams2020** [comment]
actually It is not visible, because it is in the hamburger menu.
