### ISSUE TITLE
Add Country Selector Dropdown with Flags and Phone Codes in the Contact Form

### ISSUE THREAD

**Issue by vcerpasalas** [aslams2020/Stark-Tech-Portfolio#283]
I propose adding a Country Selector Dropdown to the form, featuring flags and phone codes for all countries, alongside a designated space for users to enter their phone numbers. This enhancement will simplify the process of selecting the correct country and code, allowing users to easily find their respective codes without manual searching.

Implementing this feature will improve the user experience by reducing errors and ensuring accurate phone number entry. It will create a more inclusive platform for a global audience, demonstrating a commitment to accessibility and professionalism while streamlining form completion for users.

Please give me this issue to work on it ASAP. This is for GSSoC'24-Extd.
Thank you.

**Comment by Nivedita-Chhokar** [comment]
hey, can i be assigned?

**Comment by vcerpasalas** [comment]
Hi, @aslams2020 I am working on it today. I will send it at EOD (31st October, EST time). Thank you

**Comment by vcerpasalas** [comment]
@aslams2020 sent my pull request. Could you confirm everything is okay?
