### ISSUE TITLE
 Feature Request: Improve Appearances Section Layout

### ISSUE THREAD

**Issue by vcerpasalas** [aslams2020/Stark-Tech-Portfolio#284]
I propose restructuring the Appearances section by organizing the movie images into a two-column grid layout. Currently, the images are stacked vertically, which makes navigation cumbersome as users have to scroll extensively to view all the options.

By implementing a grid format, users will be able to see more content at a glance, enhancing the overall user experience. This change will make it easier for visitors to browse through the movies, allowing them to quickly find what they are looking for without excessive scrolling, thereby creating a more efficient and visually appealing interface.

Please give me this issue to work on it ASAP. This is for GSSoC'24-Extd.

Thank you!

**Comment by aslams2020** [comment]
The current layout looks good to have the layout. 
You can find and raise new issues.
