### ISSUE TITLE
Contact Form Not Responsiveness on Mobile

### ISSUE THREAD

**Issue by Suhani180** [aslams2020/Stark-Tech-Portfolio#287]
![Responsiveness issue in mobile ](https://github.com/user-attachments/assets/6490a8f7-5728-4739-b4ba-b2054ab0bfe5)

The contact form section on the website is not fully optimized for mobile devices. Text fields and buttons appear misaligned or cut off on smaller screens, making it difficult for users to interact with the form.

**Comment by aslams2020** [comment]
it is updated.
