### ISSUE TITLE
Social media buttons don't work

### ISSUE THREAD

**Issue by shahanxd** [aslams2020/Stark-Tech-Portfolio#288]
The social media icons in the footer are not linked to respective handles.
![Screenshot 2024-10-28 131743](https://github.com/user-attachments/assets/5cc9aaff-f3dd-4e39-b389-6498232dc30b)

I'll link them to apt handle links, such that they open in new tab when clicked.

Please assign me this issue, I'll be grateful to you and happy to work on it, thanks! :)

**Comment by shahanxd** [comment]
@aslams2020 please have a look and assign the issue, thanks!

**Comment by aslams2020** [comment]
We kept it as it is, we dont actually need to put links there. 

you can still find and raise new issues.
