### ISSUE TITLE
Improve social media icons with enhancement in hover effects

### ISSUE THREAD

**Issue by VidhanThakur09** [aslams2020/Stark-Tech-Portfolio#294]
# Description
The current social media icons have very basic styling , improving social media icon style and enhancing the styling and adding hover effect on icons would greatly improve the user experience and website presentation

- Format social media for better visual appeal.
- Improving the hover effects on social media icons.

### Current Icons Styling 

https://github.com/user-attachments/assets/ab1a5827-66ff-41b5-8313-4101a7759129

### Mock Up

https://github.com/user-attachments/assets/869c373b-1981-497a-bfb2-9cabfd9cd95f

@aslams2020 can you assign this issue to me with labels "gssoc-ext" with levels and "hacktoberfest-accepted";

**Comment by VidhanThakur09** [comment]
@aslams2020 can you please review this Issue.

**Comment by aslams2020** [comment]
Hi @VidhanThakur09 The current footer's social icons are good in hovering effects.
Also the footer across all the other pages have been updated to be the same as homepage. 

You can still find and raise new issues.

**Comment by VidhanThakur09** [comment]
Thank you for letting me know.
