### ISSUE TITLE
[UI] - Responsiveness on Copyright Footer 

### ISSUE THREAD

**Issue by Dhavisco** [aslams2020/Stark-Tech-Portfolio#305]
Hello team, I would like to work on the responsiveness of the Copyright session of the UI
See Screenshot below

![image](https://github.com/user-attachments/assets/b0575680-f384-4388-b14e-79d478b06deb)

**Comment by aslams2020** [comment]
I want you to make the overall footer responsive. Let me know if you can?

**Comment by Dhavisco** [comment]
Yes I can
I will work on it.

**Comment by aslams2020** [comment]
Go ahead!
