### ISSUE TITLE
apperances page dosen't have the scroll to top button

### ISSUE THREAD

**Issue by 2004pra** [aslams2020/Stark-Tech-Portfolio#306]
please assign me this issue under gssoc extd 24, hactoberfest
@aslams2020 
please assign me this one at least level 2 this time

**Comment by aslams2020** [comment]
@2004pra As this is a minor issue to be given level1. i am giving you additional task -
Add scroll to top button in 
- Appearances page
- Achievements page (in footer "Remarkable achievements" 

Sorry it can't be given level2.

**Comment by 2004pra** [comment]
With additional level 2 please

**Comment by aslams2020** [comment]
@2004pra actually, it is a minor issue as the scroll to top button is present in other pages, you'll just need to include from there to these pages. Hence it can be a level1 only. 

you can raise more issues in future which may considered as a level2.
i hope u understand.

**Comment by 2004pra** [comment]
Yes, I understand.
