### ISSUE TITLE
Ui of footer 

### ISSUE THREAD

**Issue by aditya07389** [aslams2020/Stark-Tech-Portfolio#309]
hello @aslams2020 

I just noticed that there is some inconsistency in the ui of footer in terms and conditions page .
![image](https://github.com/user-attachments/assets/97169740-7907-4f74-930b-ed0c14190f2f)

ill try making the ui better 

if you decide to assign this to me kindly add the gssoc extd labels 

Thankyou !

**Comment by aslams2020** [comment]
Hi, Check other pages footer too. And please fix wherever it's broken.

**Comment by aditya07389** [comment]
Sure @aslams2020

**Comment by aditya07389** [comment]
I'll raise PR by tomorrow

**Comment by aslams2020** [comment]
@aditya07389

**Comment by aditya07389** [comment]
hey @aslams2020 i got caught up in some work , i can raise pr by tomorrow if thats okay ?

**Comment by aslams2020** [comment]
Yeah @aditya07389 You can raise it by tomorrow.
Actually other contributors are yet to be assigned to footer works to avoid conflicts.

**Comment by aditya07389** [comment]
i get it , ill finish the work by tomorrow for sure

**Comment by aslams2020** [comment]
@aditya07389 is it done?

**Comment by aditya07389** [comment]
Just started
