### ISSUE TITLE
Feat: jarvis 

### ISSUE THREAD

**Issue by Aditya90456** [aslams2020/Stark-Tech-Portfolio#311]
adding jarvis bot
![Question Paper and 14 more pages - Personal 2 - Microsoft​ Edge Beta 10_30_2024 9_52_50 AM](https://github.com/user-attachments/assets/f26bfb89-e321-4d72-b44c-58d6ae8cd1b4)

**Comment by aslams2020** [comment]
Hi, Acc. to our website's theme and context, we dont require the chatbot.
