### ISSUE TITLE
Add "Back to Top" Scroll Button in README

### ISSUE THREAD

**Issue by T-Fathima** [aslams2020/Stark-Tech-Portfolio#312]
Currently, the README file does not include a "Back to Top" button, making it difficult for users to navigate back to the beginning after scrolling through lengthy sections. Adding a "Back to Top" link at the end of  readme file will improve navigation, providing a better user experience for readers.

@aslams2020 I would like to work on it.
Please assign it to me under gssoc-ext and hacktoberfest.

**Comment by aslams2020** [comment]
Its already there.
