### ISSUE TITLE
Enhancing UI Responsiveness - Hero Section of the Landing Page

### ISSUE THREAD

**Issue by Dhavisco** [aslams2020/Stark-Tech-Portfolio#315]
Hi Team,

I would like to work on the responsiveness of the hero section.
It is not well aligned on smaller devices.

Kindly check the screenshot
![image](https://github.com/user-attachments/assets/56ad0e7a-c467-477e-ac37-cae0c629b94b)

**Comment by aslams2020** [comment]
Level will be given based on the work. Please go ahead.

**Comment by srivishnu2805** [comment]
@aslams2020 The whole website is not responsive can you assign me so that I can make this whole website responsive?
like 
![image](https://github.com/user-attachments/assets/1687f781-8725-4436-b2d7-7203d78bee2f)

**Comment by aslams2020** [comment]
![image](https://github.com/user-attachments/assets/8a9e17e4-18a2-4d99-8568-0a809ad33a83)
Already resolved and merged
