### ISSUE TITLE
Improving UI of the project

### ISSUE THREAD

**Issue by Vd7905** [aslams2020/Stark-Tech-Portfolio#32]
<img width="953" alt="gssoc" src="https://github.com/user-attachments/assets/374c0355-ebe4-4b6d-858f-ba3afb96f8fd">
There is no margin between the submit button and the footer top-line.Both the lines merges with each other this can be improved so the overall ui looks  better.
@aslams2020 assign this to me i will fix this.

**Comment by aslams2020** [comment]
The issue has been already assigned to someone.  #19 
You can still raise new issues.
