### ISSUE TITLE
comics, stickers, videos, variants page dosen't have progress bar at the top of the page ..

### ISSUE THREAD

**Issue by 2004pra** [aslams2020/Stark-Tech-Portfolio#322]
please assign me this issue under gssoc extd 24 , hacktober fest 
and please atleast this time give me level 2 sir 
this one is truly a hard job please sir a level 2 
@aslams2020

**Comment by aslams2020** [comment]
Add it to all the pages where it is absent.

**Comment by 2004pra** [comment]
Ok

**Comment by aslams2020** [comment]
@2004pra is it done?

**Comment by 2004pra** [comment]
No not yet. Will be done today

**Comment by 2004pra** [comment]
sir because of some reason i am not able to complete the task today

**Comment by 2004pra** [comment]
will it be okay if i do it tommorow

**Comment by aslams2020** [comment]
Fine! Create a PR today then

**Comment by aslams2020** [comment]
Will close this issue today. Create a PR before that,

**Comment by 2004pra** [comment]
i don't know but for sum reason the progress bar is not visible at videos
page so i am skipping that one
