### ISSUE TITLE
Appearances tab name is duplicated

### ISSUE THREAD

**Issue by RushilJalal** [aslams2020/Stark-Tech-Portfolio#324]
Here's the screenshot:
I propose to remove the 2nd header with the text 'Appearances' just below the navbar, since it is duplicated and doesn't follow the general website design

I would like to work on this issue. Thanks.

![image](https://github.com/user-attachments/assets/c0cb4c6c-3f4c-4222-b72f-ea8ec3d79530)

**Comment by aslams2020** [comment]
resolved #337
