### ISSUE TITLE
Social links in footer don't work

### ISSUE THREAD

**Issue by RushilJalal** [aslams2020/Stark-Tech-Portfolio#325]
Here's the screenshot: 
The social links are not correct. Currently, all of them route back to the same website, which is incorrect.
I kindly request the mod to provide me with the correct social links.
I want to work on this issue by adding the necessary links and remove other unnecessary links which makes no sense for this page.

![image](https://github.com/user-attachments/assets/9ef5e98f-5305-474e-b4d3-b21149320620)

**Comment by aslams2020** [comment]
We purposely kept it dummy
