### ISSUE TITLE
 Repeating Header and Section upon Scrolling in Variant section

### ISSUE THREAD

**Issue by saadgibawa** [aslams2020/Stark-Tech-Portfolio#326]
When scrolling down the page, the "Variants" section, along with the header, repeats unexpectedly. This results in a duplicated appearance of the header and section content, which disrupts the user experience and causes visual clutter.
![Screenshot 2024-10-31 114518](https://github.com/user-attachments/assets/258c3bff-a97c-4bfd-95e2-d63934bb7a2f)

**Comment by aslams2020** [comment]
Please fix it. Also, if there are similar minor issues in other page please check nd fix it

**Comment by aslams2020** [comment]
The footer's UI broke issue is assigned to someone else, so other than footer if any issue like above, Please fix it @saadgibawa

**Comment by saadgibawa** [comment]
@aslams2020 Okay

**Comment by saadgibawa** [comment]
@aslams2020 Should I update the scroll to top button in this section to match the one on the homepage and other pages?

**Comment by aslams2020** [comment]
No, I have updated the one in the homepage. @saadgibawa 
![image](https://github.com/user-attachments/assets/dd9d5bbf-73cc-41c2-b9a8-136866fc0a39)

**Comment by saadgibawa** [comment]
yes thats what i am saying that the button is different in variant section and appearances section also. 
![image](https://github.com/user-attachments/assets/99ef3534-059a-47bb-bc88-cbbcb6cd282b)

**Comment by aslams2020** [comment]
Ohkay, then update it!
Thanks for noticing

**Comment by saadgibawa** [comment]
Okayy
