### ISSUE TITLE
Footer Misalignment

### ISSUE THREAD

**Issue by saadgibawa** [aslams2020/Stark-Tech-Portfolio#327]
The footer is not aligned properly, resulting in an uneven or uncentered appearance, which disrupts the layout and visual balance of the page. This misalignment affects the user experience, particularly on larger screens where the footer sections may appear disproportionate or disorganized.
![Screenshot 2024-10-31 115108](https://github.com/user-attachments/assets/0afed9d0-6e56-4f98-a2b0-7d9fdf0a159b)

**Comment by aslams2020** [comment]
Currently, Someone is working on footer. Will assign you after that work is complete.

**Comment by saadgibawa** [comment]
Sure!

**Comment by aslams2020** [comment]
@saadgibawa You can start working on it. level will be assigned based on the work

**Comment by saadgibawa** [comment]
@aslams2020 Hey! I have been working on the footer section alignment issue for a few days now. I've tried pretty much everything I can think of and even did some research, but I still haven't gotten anywhere. Right now, it looks like this:  
![Screenshot 2024-11-06 211913](https://github.com/user-attachments/assets/af4653bd-519e-458b-9ceb-5bdf59887ceb)

Here's how it currently looks:  
![image](https://github.com/user-attachments/assets/bc483d19-6e8c-4995-b107-08d8952ad823)

Please help me out with this

**Comment by aslams2020** [comment]
Maybe you can include the footer section present in home page as it is in other pages?

**Comment by saadgibawa** [comment]
I’ve tried adding the footer from the homepage to the other pages, but the alignment problem is still there.

**Comment by saadgibawa** [comment]
I figured out what exactly was causing the footer misalignment on all the pages and got it fixed. 
Now it looks like this: 
![image](https://github.com/user-attachments/assets/1d514c0d-d221-4d93-8de0-a4655b252e7c)
But the bottom gap is still there so I'm currently reviewing the entire code to understand why the gap won’t go away. It's going to take me a bit to fix the bottom gap. I’ll let you know when I’m all done! Appreciate the help though!

**Comment by aslams2020** [comment]
Yeah, let me know when it's done!

**Comment by saadgibawa** [comment]
I'm done with this issue and raised a PR just now. Please review it. Thanks!

**Comment by saadgibawa** [comment]
Also at present the logo in the footer section of stickers and blogs page is not aligned
![image](https://github.com/user-attachments/assets/09a98429-4b9a-4f21-b0e3-7cb8de4415bc)
Should i fix this also if it is not assigned to someone else?
