### ISSUE TITLE
[BUG]Navigation and Display Issues in Comics and Appearances Sections

### ISSUE THREAD

**Issue by SAURABHM6341** [aslams2020/Stark-Tech-Portfolio#329]
There are several navigation and layout issues affecting the Comics and Appearance sections:

Missing Active Link Indicator: When on the Comics page, the Comics navigation link does not display an active state (e.g., underline or highlight), causing confusion for users about their current location on the site.

current state:

![issue1](https://github.com/user-attachments/assets/7a6ff38d-434a-4f42-aa46-8cd8a24fcb2a)

Missing Navigation Link: There is no link provided to navigate from the Comics page to the About page, which impacts user navigation and flow.

Hidden Page Heading in Appearance Section: On the Appearance page, the heading text is obscured behind the navbar, likely due to layout or spacing issues. This affects readability and the visual structure of the page.

current state:

![issue 2](https://github.com/user-attachments/assets/5e1b73dd-0ceb-453c-9e0f-f7ca7bb29eae)

[Yes] I have checked for the issue if it already exist or not.
--> I am contributer in GSSoc extended 24.
--> Please assign this issue to me, I have required knowledge to solve this.

**Comment by aslams2020** [comment]
fixed #337
