### ISSUE TITLE
change font styling

### ISSUE THREAD

**Issue by shivamy009** [aslams2020/Stark-Tech-Portfolio#33]
change font styling for more interactive

**Comment by aslams2020** [comment]
Can you Please elaborate more on this.

**Comment by shivamy009** [comment]
> Can you Please elaborate more on this.

Which Cinematic Universe Does He Belong? in this section font is not beautiful it can be changed for more attractive

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @aslams2020
