### ISSUE TITLE
Enhancing the Contact us prompt

### ISSUE THREAD

**Issue by Prachiikhar25** [aslams2020/Stark-Tech-Portfolio#331]
Hello I'd like to enhance the prompt in Contact us section 
which would be more attractive to read and reachable 

![{44C11B27-EF2F-4AA9-93D0-5344A44076AF}](https://github.com/user-attachments/assets/60604665-28de-4e81-a600-9695d3a81a8d)

Thanks!

**Comment by aslams2020** [comment]
Hi, This issue cannot be given level1.
