### ISSUE TITLE
Adding an interactive quiz on ironman movies for viewer interaction✨

### ISSUE THREAD

**Issue by shriyadindi** [aslams2020/Stark-Tech-Portfolio#342]
I would like to add an interactive quiz on ironman movies for viewer interaction, kindly assign me the task.

**Comment by aslams2020** [comment]
Level will be assigned based on the work

**Comment by shriyadindi** [comment]
@Okay

**Comment by shriyadindi** [comment]
@aslams2020 I've done added the quiz, kindly go through.
https://github.com/aslams2020/Stark-Tech-Portfolio/pull/351
