### ISSUE TITLE
Improve the UI of the footer section in the privacy policy page

### ISSUE THREAD

**Issue by Antima2004** [aslams2020/Stark-Tech-Portfolio#346]
Need a Improvement in  the UI of the footer section in the privacy policy page which makes your website looks consistent.
![Screenshot 2024-11-01 161610](https://github.com/user-attachments/assets/f7d663e1-9ce3-4afc-b727-521de163f40b)

**Comment by aslams2020** [comment]
Assigned to #309 

You can still find and raise issues.
