### ISSUE TITLE
Want to add security 

### ISSUE THREAD

**Issue by Dipanita45** [aslams2020/Stark-Tech-Portfolio#347]
Plaese assign me the issue 
@aslams2020

**Comment by aslams2020** [comment]
Which security?

**Comment by Dipanita45** [comment]
Added security of the website

**Comment by aslams2020** [comment]
please elaborate more

**Comment by Dipanita45** [comment]
Add necessary security to protect the website against the harms

**Comment by Dipanita45** [comment]
Please assign me the issue

**Comment by aslams2020** [comment]
Please raise other issue in the repo. 
As for our website we dont need security ig..

You can still find and raise new issues

**Comment by Dipanita45** [comment]
Okay
