### ISSUE TITLE
[BUG] Improve Contributors page 🔴 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [aslams2020/Stark-Tech-Portfolio#350]
🔴This contributor page doesn't display all contributors. which doesn't look good... This contributors page only displays 30 contributors but your total contributors are 45+

🟢I want to Fixed this issue properly.

PA please assign me this task.

![Screenshot 2024-11-01 205710](https://github.com/user-attachments/assets/4574ddda-9cd9-4abe-8654-3ce4e5c76043)
![Screenshot 2024-11-01 205731](https://github.com/user-attachments/assets/f6f8f38a-0ff0-4b3a-8bec-f9b62daa4f36)

**Comment by Subhajit-2023-44** [comment]
@aslams2020

**Comment by aslams2020** [comment]
Go ahead

**Comment by aslams2020** [comment]
@Subhajit-2023-44 Done?

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 Done?

Done #398
