### ISSUE TITLE
Enhanced scroll back button with timeline on it for smoother functioning.

### ISSUE THREAD

**Issue by shriyadindi** [aslams2020/Stark-Tech-Portfolio#357]
Enhanced scroll back button with timeline on it for smoother functioning.
![Screenshot 2024-10-31 115055](https://github.com/user-attachments/assets/d5f28ff3-f727-4a10-bd2a-2063a0ca6628)

**Comment by aslams2020** [comment]
Please do that in each page's Scroll-to-top button.

**Comment by shriyadindi** [comment]
@aslams2020 Okay

**Comment by shriyadindi** [comment]
@aslams2020 Done
