### ISSUE TITLE
ADD a Social media -Icon in footer section

### ISSUE THREAD

**Issue by Pooja3Bhattrai** [aslams2020/Stark-Tech-Portfolio#36]
Hello @aslams2020 , there is missing social media icons like facebook, twitter,etc.

please assign this issue to me :)

**Comment by riyarane46** [comment]
hii @aslams2020    i believe i can do this task efficiently as i have a strong hold over css styling. could you please assign me this task under GSSoC24 extd and hactoberfest24.

**Comment by aslams2020** [comment]
@Pooja3Bhattrai Go ahead.
Add : Github, X, Linkedin, Facebook
![image](https://github.com/user-attachments/assets/810ff5ff-d23d-4729-943b-25c003603860)

**Comment by Pooja3Bhattrai** [comment]
Ok sure @aslams2020

**Comment by rutikakengal** [comment]
I like to add social media icons and description about the webpage Assign me @aslams2020

**Comment by Pooja3Bhattrai** [comment]
> @Pooja3Bhattrai Go ahead. Add : Github, X, Linkedin, Facebook !

it is done, you may review it.
