### ISSUE TITLE
Adding a Separate section for FAQs

### ISSUE THREAD

**Issue by shivenyadavs** [aslams2020/Stark-Tech-Portfolio#363]
In this section all the description will be given about the general queries 
like how to access comics section
how to contact the team
watch latest releases 
and more

**Comment by aslams2020** [comment]
#244 working on it

**Comment by aslams2020** [comment]
Make a Separate page for it.
Add the link to it in the footer section's FAQ link(already present there)

**Comment by aslams2020** [comment]
level will be assinged based on the words

**Comment by aslams2020** [comment]
Work*

**Comment by shivenyadavs** [comment]
ok
