### ISSUE TITLE
Adding effects on Ironman Homepage picture

### ISSUE THREAD

**Issue by AyutheCoder** [aslams2020/Stark-Tech-Portfolio#39]
![iron](https://github.com/user-attachments/assets/b896b72b-0045-4a10-bfe7-c79f505cf307)
Can put some effects on Ironman image when it is hovered and some background effects also.

**Comment by AyutheCoder** [comment]
Please provide GSSOC Ext 24 and Hactoberfest label to it,I can improve this

**Comment by riyarane46** [comment]
hii @aslams2020    i believe i can do this task efficiently as i have a strong hold over css styling. could you please assign me this task under GSSoC24 extd and hactoberfest24.

**Comment by aslams2020** [comment]
@AyutheCoder Can you do something like - The image always floats smoothly ? along with the text on it's left side. 
Both speed should be smooth and steady.

**Comment by AyutheCoder** [comment]
@aslams2020 ,Yes Sir,I can do this

**Comment by AyutheCoder** [comment]
Thank you Sir,now I can start working ?

**Comment by aslams2020** [comment]
Yeah, Go ahead you are assigned.
