### ISSUE TITLE
redirect and alignment bugs

### ISSUE THREAD

**Issue by saadgibawa** [aslams2020/Stark-Tech-Portfolio#393]
1. The logo in the footer section of stickers, merchandise, blogs page is not aligned
2. The redirect links in navbar of quiz page are not working
3. The redirect link of about section in the navbar of stickers, merchandise page is not working
4. The arrow of the back to top button in the achievements page is not there
5. The redirect link of appearances section in the navbar of villain page is not working
6. The back to top button is different in some pages

**Comment by aslams2020** [comment]
Great!

**Comment by saadgibawa** [comment]
which one back to top button should i apply on all pages?
this 
 ![image](https://github.com/user-attachments/assets/2a54cc60-7f92-4b6f-b5c3-9279888320f6)
or this
![Screenshot 2024-11-08 155731](https://github.com/user-attachments/assets/06158861-0411-42ba-95ba-d737826fd7b2)

**Comment by aslams2020** [comment]
The above one looks good. 
If you would like to add highlight shadow to that you can, else keep that as it is

**Comment by saadgibawa** [comment]
I have added the glow effect as it is in the header and footer logo. Is this fine or should i try something else?

https://github.com/user-attachments/assets/c7af0145-d9cc-4151-813a-59d5ce67ec9b

**Comment by aslams2020** [comment]
Yeah, it's good. You can create a PR
