### ISSUE TITLE
FEATURE: Add Dark Mode Toggle

### ISSUE THREAD

**Issue by shubhagarwal1** [aslams2020/Stark-Tech-Portfolio#40]
**Feature Request**
- Implement a dark mode toggle feature on the website to enhance user experience, especially for users browsing at night or in low-light environments.

**Approach**
- Add a switch in the navigation bar to allow users to toggle between light and dark mode. Ensure that the website's entire color scheme, including text, background, buttons, and icons, adapts dynamically.
Hey @aslams2020 please allow me to add this feature
assign me with this issue with label (gssoc-ext and level)

**Comment by aslams2020** [comment]
We currently don't need that feature to be implemented
