### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by saadgibawa** [aslams2020/Stark-Tech-Portfolio#413]
1. No footer in variants page
2. No header and footer in achievements page
3. Footer links in Privacy policy and terms&conditions page are not working
4. Fun fact box not working properly in variants and achievements page
![Screenshot 2024-11-08 223129](https://github.com/user-attachments/assets/9279d460-893d-41ea-b5a4-dc731a5e0fc0)
5. Font of fun fact is different in quiz page than other pages
![Screenshot 2024-11-08 215945](https://github.com/user-attachments/assets/74f9a5db-9d7b-4b4e-bd31-9a90a7aaa0ff)

**Comment by aslams2020** [comment]
That's great, Go ahead

**Comment by saadgibawa** [comment]
Also the logo in the footer section of wallpaper page is also not aligned. Should i also fix that within this issue?

**Comment by aslams2020** [comment]
Yeah fix it
