### ISSUE TITLE
add voting system

### ISSUE THREAD

**Issue by Riyachauhan11** [aslams2020/Stark-Tech-Portfolio#419]
adding an option that lets user vote for their fav movie outta the given movies in movie page

**Comment by BrindaManani** [comment]
Can you provide more details on the point you mentioned...
Is it like a voting poll as a popup activity for users, or a star rating system below each movie title ?

**Comment by Riyachauhan11** [comment]
> Can you provide more details on the point you mentioned... Is it like a voting poll as a popup activity for users, or a star rating system below each movie title ?

It would be either a popup on the movies page or be present inside a button that will let users pick 1 movie title from all the movie titles present  on page (given as options in the vote thing)

**Comment by BrindaManani** [comment]
I think popup voting is a better option.
Go ahead.
