### ISSUE TITLE
Add movies page which conists of all the iron-man movies

### ISSUE THREAD

**Issue by yeshwanth-ds** [aslams2020/Stark-Tech-Portfolio#43]
I would like to create a movire page where it consists of all the iron-man movies, Which consit of a movie poster, name, duration, ratings, descriptio..etc 
I will aslo make sure that the theam of this page matches with the original page.
This page will open when movies  anchor is clicked.
![Screenshot 2024-10-02 030726](https://github.com/user-attachments/assets/c6691502-0227-4e62-b594-c91bb7d63fe9)

I would like you to assigne me this task under gssoc-ext

**Comment by aslams2020** [comment]
Already assigned #8
