### ISSUE TITLE
Footer is too large, needs to be resized

### ISSUE THREAD

**Issue by myselfshivams** [aslams2020/Stark-Tech-Portfolio#44]
The current footer size is too large and disproportionate to the rest of the layout. It impacts the overall user experience, especially on smaller screens. The footer needs to be resized and adjusted to fit better with the rest of the design, maintaining responsiveness and usability across different devices.

Labels: GSSoC, Hacktoberfest

@aslams2020 Please assign this issue to @myselfshivams.

**Comment by Aryan01903** [comment]
Hello,
I am Aryan Kumar Shrivastav, I can resolve this problem please assign this to me

**Comment by aslams2020** [comment]
Already Fixed.
