### ISSUE TITLE
Add Iron Man origin Story Page With animation.

### ISSUE THREAD

**Issue by coderrrx-Brijesh** [aslams2020/Stark-Tech-Portfolio#46]
Want to add a Iron Man origin story Page with some animation and want cover origin story. It will accessible from 'Iron man Introduction' Section.

**Comment by PThanushree** [comment]
Can you please assign this to me under @gssoc-24 extnd and hactoberfest.

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @aslams2020

**Comment by aslams2020** [comment]
> Want to add a Iron Man origin story Page with some animation and want cover origin story. It will accessible from 'Iron man Introduction' Section.

I liked the idea, sorry for the delay caused due to my account disabled. 
Can u just give an idea about what this page will contain exactly?

**Comment by aslams2020** [comment]
@coderrrx-Brijesh
