### ISSUE TITLE
Add a Detailed CONTRIBUTING.md File

### ISSUE THREAD

**Issue by say-het** [aslams2020/Stark-Tech-Portfolio#49]
Hey @aslams2020,

**Description**:  
The project currently lacks a `CONTRIBUTING.md` file, which is crucial for guiding new contributors, especially those participating in events like **GSSoC-Extd 2024**. A comprehensive contribution guide will streamline the contribution process and help maintain consistency in the codebase.

The following sections should be included:
- Forking and cloning the repository.
- Branching strategy for new features or bug fixes.
- Requesting assignment for issues.
- Coding standards and best practices (HTML, CSS, JavaScript).
- Testing and validation before submitting a PR.
- Writing meaningful commit messages.
- Submitting a pull request and the review process.
- Code of Conduct reference.

**Additional Context**:
- This will be beneficial for ensuring smooth collaboration, especially with new contributors.
- The `CONTRIBUTING.md` will outline the steps and standards that must be followed, ensuring clarity in the contribution workflow.

I would like to contribute this `CONTRIBUTING.md` file to improve the project's onboarding process.

PLEASE Assign me this under GSSoC-2024 Extd.

Little about me: I am an experienced contributor as I have successfully completed Hacktoberfest-2020 and Hacktoberfest-2023 and GSSoC-2024.

**Comment by riyarane46** [comment]
hii @aslams  i believe i can do this task efficiently . could you please assign me this task under GSSoC24 extd and hactoberfest24.

**Comment by aslams2020** [comment]
@say-het Go ahead.
