### ISSUE TITLE
Contact part

### ISSUE THREAD

**Issue by Mahy-31** [aslams2020/Stark-Tech-Portfolio#5]
Improvising the contact page part which relates to the color palette and is attractive as well. With my experience in UI/UX design and web development, I believe i could resolve this issue. Could you please assign me this task?

**Comment by riyarane46** [comment]
@aslams2020 , i believe i could solve this issue , could you please assign it me . i have a strong background of html and css .

**Comment by shraddhabaghel** [comment]
@aslams2020 Due to my expertise in resolving HTML issues and make it more interactive , I think i can contribute on this issue.Please assign me this

**Comment by shraddhabaghel** [comment]
# Previous Features:
1.Semi-transparent black background with an image for visual appeal.
2.Input fields for the user’s name, phone number, and email.
3.Responsive design with a maximum width for consistency across devices.
4.Clearly styled submit button for easy user interaction.

#Later Changes:
1.Added labels for each input field to improve accessibility and user guidance.
2.Assigned unique IDs to input fields for better identification and form handling.
3.Improved styling for input fields for a more modern look.
4.Added hover effects to the submit button for better interaction.
![Contact](https://github.com/user-attachments/assets/f01cce30-824d-4dc1-9577-9f53128c27e8)
Please assign me this issue to add all the features that i modified.

**Comment by aslams2020** [comment]
> Improvising the contact page part which relates to the color palette and is attractive as well. With my experience in UI/UX design and web development, I believe i could resolve this issue. Could you please assign me this task?

@Mahy-31 Can you please elaborate more on your idea?

**Comment by aslams2020** [comment]
@shraddhabaghel The issues can be assigned on first come basis. you can still raise new issues.

**Comment by Mahy-31** [comment]
> > Improvising the contact page part which relates to the color palette and is attractive as well. With my experience in UI/UX design and web development, I believe i could resolve this issue. Could you please assign me this task?
> 
> @Mahy-31 Can you please elaborate more on your idea?

The problem with the contact page is that its design can be enhanced which will be more attractive like the label thing and the input bar, etc. As an ui/ux designer i believe that I could help you with the best and attractive design for the contact page.

**Comment by aslams2020** [comment]
@Mahy-31 Okay, assigning you as you were the first to raise issue on this part.
Go ahead.

**Comment by aslams2020** [comment]
Make sure you follow the Website design theme

**Comment by Mahy-31** [comment]
> Make sure you follow the Website design theme

Sure. Thank you for assigning me this one. Will come up with an attractive design

**Comment by aslams2020** [comment]
@Mahy-31 Any updates?
