### ISSUE TITLE
Include an About Page

### ISSUE THREAD

**Issue by Mayursoni1518** [aslams2020/Stark-Tech-Portfolio#50]
Enhance the Contact Us Form and Include an About Page

To improve the user experience, it is essential to enhance the Contact Us form for better usability and accessibility. Additionally, adding an About Page will provide visitors with valuable information about the organization, its mission, and its values.

If you believe these improvements are crucial for your website, they will foster user engagement, build trust, and create a more informative and user-friendly interface.
Please assign this issue to me under the Gssoc extd'24.

**Comment by aslams2020** [comment]
@Mayursoni1518 Make the About Page Only and link it to the navbar. 
Go ahead. Make sure to follow website theme

**Comment by Mayursoni1518** [comment]
Thanks

**Comment by Mayursoni1518** [comment]
Hi @aslams2020  can you explain the description of the About page I am genuinely confuse about that

**Comment by aslams2020** [comment]
@Mayursoni1518 , Mention that the website is inspired by the tech-savvy, futuristic world of Tony Stark (Iron Man), and aims to showcase cutting-edge skills, projects, and innovation.

Mention values such as innovation, creativity, continuous learning, and passion for technology. For example: "We believe in pushing the boundaries of technology, just like Tony Stark, and strive to create projects that make a difference."

Our vision, Join us on our journey .
etc..

**Comment by aslams2020** [comment]
Also include images. And Make sure you follow website theme.
(Level will be assigned based on the work, so dw abt it)

**Comment by aslams2020** [comment]
@Mayursoni1518 any updates?

**Comment by Mayursoni1518** [comment]
Can I submit it by tomorrow... 
Actually I am out right now from home

**Comment by Mayursoni1518** [comment]
I didn't remember clearly but something is when I raised this issue About us page was not include in your website...but i just see now about page is already include ( that is superb not even need adjustment )....so should i reassign this issue ???

**Comment by aslams2020** [comment]
@Mayursoni1518 There's no About us page in the website. 
Yeah in homepage there's about section which is about tony stark. we want the page for our website

**Comment by aslams2020** [comment]
Will you work on it? or should i assign to someone else.
let me know

**Comment by Mayursoni1518** [comment]
> Will you work on it? or should i assign to someone else.
> let me know

You can assign it to someone else 
Thank you so much for your time ✨

**Comment by aslams2020** [comment]
@rutikakengal Are u willing to work on this issue  ?

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?
