### ISSUE TITLE
Linking Contact section to email.

### ISSUE THREAD

**Issue by aadhi-i** [aslams2020/Stark-Tech-Portfolio#51]
When someone sends a message it can be received via email, I can set it up. Please include gssoc ext , hacktoberfest and level. Also please do mention the mail id which the messages should be received.

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @aslams2020

**Comment by NausheenShaikhAyyub** [comment]
I would like to work on this, Kindly assign to me @aslams2020
