### ISSUE TITLE
I want to work on Movies button and merchandise

### ISSUE THREAD

**Issue by subin-shk** [aslams2020/Stark-Tech-Portfolio#53]
The movie button is not functioning and there is no merchandise mentioned. I want to work on the movie button and add merchandise.

Please assign me with this task.

**Comment by subin-shk** [comment]
GSSOC extended

**Comment by Pujitha254** [comment]
I wanted to work on both the buttons movies and video .so when we click on that it was redirected to the page where it contains all the movies of ironman and when we click video button it was redirected to the video which explains about ironman.....
![image](https://github.com/user-attachments/assets/105b2584-ec7c-44a6-9b57-90b961e631d9)
