### ISSUE TITLE
FEATURE: Automated Greeting Workflow

### ISSUE THREAD

**Issue by samyak-aditya** [aslams2020/Stark-Tech-Portfolio#55]
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

Hey @aslams2020  please assign me this task with label "gssoc-ext" and "level1"

**Comment by aslams2020** [comment]
@samyak-aditya go ahead.

**Comment by samyak-aditya** [comment]
Hey @aslams2020 can you also add label "level1" 
I would highly appreciate that 
Thanks

**Comment by samyak-aditya** [comment]
Hey @aslams2020 I have raised the PR
Thanks
