### ISSUE TITLE
Can add scroll animation on the elements of the webpage.

### ISSUE THREAD

**Issue by Vatsal-Verma** [aslams2020/Stark-Tech-Portfolio#57]
you can assign this to me :)

**Comment by aslams2020** [comment]
@Vatsal-Verma Go ahead. Make sure it is smooth and doesn't disturb the scroll-flow of the website.

**Comment by rutikakengal** [comment]
I like to add Scroll button to the webpage which give to fastly go to above side of webpage  Assign me i like to work on it
