### ISSUE TITLE
on the top bar  I would like to add the movies section ,in that all the movies of iron man can be displayed in an order .so could please assign me on this 

### ISSUE THREAD

**Issue by swethapadmavathimukku** [aslams2020/Stark-Tech-Portfolio#58]
![Screenshot 2024-10-02 123025](https://github.com/user-attachments/assets/efb06259-43ef-4dc3-8824-5da74775c6bb)

**Comment by aslams2020** [comment]
Already assigned to #24 
You can still raise new issues.
