### ISSUE TITLE
Movies button

### ISSUE THREAD

**Issue by riyarane46** [aslams2020/Stark-Tech-Portfolio#59]
@aslams2020 
The movies button is not redirecting anywhere . 
i would like to create a separate page for movies where users can see the cards of movies of IRON MAN . 
i would link that page with the button and also have the main nav bar on the top so that user can go back to the home page as well . 
please assign me this issue , i would really like to work on it .

i have a strong background in web development , i believe i can complete this task . 
please assign this issue to me under GSSoC24 extended and hacktoberfest24.

**Comment by aslams2020** [comment]
Assigned to #8 

you can still find and raise new issues
