### ISSUE TITLE
Adding a section called  variants on the top  bar section 

### ISSUE THREAD

**Issue by swethapadmavathimukku** [aslams2020/Stark-Tech-Portfolio#62]
![Screenshot 2024-10-02 123025](https://github.com/user-attachments/assets/e481df94-969c-4666-8c8b-6e908aa94b55)

in that section, the different variants of Ironman is displayed, so could you please me on this issue

**Comment by aslams2020** [comment]
Instead of "variants" section.
Add a link on that image..When a user clicks on that image, the variants page should open.
(maintain separate variants.css file for it and link it in ur variants.html)

**Comment by aslams2020** [comment]
Make sure to follow website's theme.

**Comment by swethapadmavathimukku** [comment]
Thank you for assigning me as a contributor.  I will do my best to contribute to the project
I am excited to work and help in improving the project

Could you please add the level label? 

Best regards,
Swetha padmavathi mukku

**Comment by aslams2020** [comment]
Levels can be assigned based on the work. go ahead.

**Comment by swethapadmavathimukku** [comment]
okay thank you

**Comment by swethapadmavathimukku** [comment]
Yes , I have completed half of the part and may I know if there is any deadline or not

**Comment by aslams2020** [comment]
Okay.
No there's no deadline as such but Try to complete a task within 2 days so that it'll not create conflicts.
As u can see, now Our website has significant changes already,after u make a PR it may cause Conflicts to resolve

**Comment by swethapadmavathimukku** [comment]
Okay, thank you. I will finish it as soon as possible.

**Comment by aslams2020** [comment]
Yeah it's ok

**Comment by swethapadmavathimukku** [comment]
okay

**Comment by swethapadmavathimukku** [comment]
![Screenshot 2024-10-06 084204](https://github.com/user-attachments/assets/ccda18cd-abc3-48cf-81c2-eb52e5291a16)
  
may I know if any changes are required to this

**Comment by aslams2020** [comment]
Nice. You can make the PR so that I can preview it. In PR mention the issue number. 
If any changes I'll let u know.

**Comment by swethapadmavathimukku** [comment]
thank you, okay
