### ISSUE TITLE
Image of Robert Downey Jr 

### ISSUE THREAD

**Issue by riyarane46** [aslams2020/Stark-Tech-Portfolio#66]
the image looks inconsistent in comparison to the above section image card of Tony Stark and also it doesnt go well with the background . 
i would like to change the image to make the website look more attractive . 

can you please assign me this issue under GSSoC24 extd and hacktoberfest24

**Comment by anyaaseth08** [comment]
I have rectified this issue by changing the image of Robert Downey Jr so that it goes will with the rest of the website.
Assign me this task so that i can create a pull request.
![Screenshot 2024-10-04 163413](https://github.com/user-attachments/assets/e7871356-bc4c-4e5e-b630-3b37dba95923)
