### ISSUE TITLE
Navbar Issue

### ISSUE THREAD

**Issue by Shraddha-Deshmukh2119** [aslams2020/Stark-Tech-Portfolio#67]
The current navbar design lacks visual appeal and could benefit from adjustments to make it more attractive. This issue proposes changes to the navbar color scheme, font sizes, and button design for a more modern and engaging user experience.
![navbar](https://github.com/user-attachments/assets/392aeba6-0b0a-4cee-ac98-f20f1769998b)
I love to solve this issue so  i request you to assign me this issue.

**Comment by aslams2020** [comment]
Go ahead!

**Comment by rutikakengal** [comment]
I like to Work on Navbar ,the current navbar design lacks visual appeal and could benefit from adjustments to make it more attractive. This issue proposes changes to the navbar color scheme, font sizes, and button design for a more modern and engaging user experience. assign me @aslams2020

**Comment by NishantRana07** [comment]
Hi, I can design better Form and can fix the fonts and navbar issues and buttons, I have worked on projects like this please assign it to me

**Comment by aslams2020** [comment]
already assigned to @Shraddha-Deshmukh2119

**Comment by Shraddha-Deshmukh2119** [comment]
Thank you

**Comment by aslams2020** [comment]
@Shraddha-Deshmukh2119 Don't change search bar, Someone else is working on it.
Good luck

**Comment by Shraddha-Deshmukh2119** [comment]
Ok

**Comment by Shantanu675** [comment]
I believe I could solve this issue . Could you please assign it me . I have a strong background of html and css .

**Comment by Shraddha-Deshmukh2119** [comment]
I have done it

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @aslams2020

**Comment by aslams2020** [comment]
@Shraddha-Deshmukh2119 Will close the PR tomorrow morning. please try to complete it
