### ISSUE TITLE
Change a background color, font style and size and change footer section

### ISSUE THREAD

**Issue by Shraddha-Deshmukh2119** [aslams2020/Stark-Tech-Portfolio#69]
We need to enhance the webpage design by improving several key areas. First, update the background to a more attractive color scheme, possibly incorporating gradients for a modern look. Next, change the font style to a clean, modern sans-serif typeface such as Roboto or Open Sans, and adjust the font sizes for better readability, with headings sized between 32px-48px and body text between 16px-18px. The contact form should be redesigned to be more user-friendly and visually appealing by using rounded input fields, increased padding, and vibrant button colors with hover effects. Lastly, the footer section should be improved with a dark background, contrasting light text, vibrant link colors, and possibly the addition of social media icons to make it more engaging.
![back](https://github.com/user-attachments/assets/84b9afba-5db5-4640-a909-7a7ff195021d)
![form](https://github.com/user-attachments/assets/30649b57-dd16-4de6-98fd-5c11a4bcd222)
I love to solve this issue so i request you to assign me this issue.

**Comment by aslams2020** [comment]
Only make following changes  -
- update the background to a more attractive color scheme, possibly incorporating gradients for a modern look. 
- adjust the font sizes for better readability, with headings and body text between 

Other changes are assigned to somebody else

**Comment by NishantRana07** [comment]
I am up for this one , please assign this one to me.

**Comment by aslams2020** [comment]
@Shraddha-Deshmukh2119 Any updates?

**Comment by Shraddha-Deshmukh2119** [comment]
Yes, it's done.

**Comment by Shraddha-Deshmukh2119** [comment]
![githubchange](https://github.com/user-attachments/assets/ec9d7b1e-6bdd-440b-a79e-edad5245c160)
![backgroundchange](https://github.com/user-attachments/assets/96174f6c-83b5-4f87-a846-912f5efd2c4e)
![back3](https://github.com/user-attachments/assets/a039f358-9cb2-4b55-8619-a0e639f2e5a7)
I have done all the changes.

**Comment by Shraddha-Deshmukh2119** [comment]
by default i unassign me plz help me.

**Comment by Kavish-Paraswar** [comment]
Given my strong background in HTML, CSS, and JavaScript, I would like to request this task be assigned to me. I intend to mark this under the GSoC extended projects.

**Comment by aslams2020** [comment]
@Shraddha-Deshmukh2119 This design is not suitable ig.. Thankyou for your efforts but we can't change the overall UI

**Comment by ayushiu** [comment]
please assign this to me @aslams2020

**Comment by TalhaPirzada** [comment]
@aslams2020  please assign to me

**Comment by DarakshanSaara** [comment]
@aslams2020 Please assign this issue to me I can change it only as per your instructions

**Comment by Shraddha-Deshmukh2119** [comment]
I have fixed the issue.
