### ISSUE TITLE
Add "Back to Top" button

### ISSUE THREAD

**Issue by saadgibawa** [aslams2020/Stark-Tech-Portfolio#7]
![Screenshot 2024-10-01 175837](https://github.com/user-attachments/assets/a9fe0ad3-b348-4998-a404-8117c8fef419)
The submit button in the footer is very close to the white strip beneath it. Adding some vertical spacing between the submit button and the white strip would enhance the visual appeal, making the layout more spacious and organized. 
Adding a "Back to Top" button in the footer would improve the page navigation by providing users a convenient way to return to the top without excessive scrolling.
I want to work on this so please assign me this issue @aslams2020

**Comment by Gaurav075** [comment]
Please assign this issue to me. I have strong command of HTML,CSS, and Javascript @aslams2020

**Comment by aslams2020** [comment]
@saadgibawa You can start working on Back to Top Button. (keep the vertical spacing as it is, as it is assigned to someone else)
All the best!

**Comment by saadgibawa** [comment]
@aslams2020 Sure. Thankyou!

**Comment by kjvlasyapriya** [comment]
By adjusting the internal spacing and space around the footer the elements inside the footer gives neat and organized look.
Adding a "Back to top" button provides a quick way to return to top of the page which is very useful for long scrolling websites. It is placed in a corner and when it is clicked it smoothly scroll the page back to the top.
I want to work on this so please assign me this issue @aslams2020

**Comment by aslams2020** [comment]
@saadgibawa How's it going?
