### ISSUE TITLE
improve the README file

### ISSUE THREAD

**Issue by adityakalburgi** [aslams2020/Stark-Tech-Portfolio#70]
Hi!
I'd like to contribute by improving the README file. Could you please assign this issue to me? Thanks!

**Comment by aslams2020** [comment]
What changes are u planning to make? please elaborate.

**Comment by adityakalburgi** [comment]
@aslams2020  can provide a brief overview of this project,  features, techstack, better installation guide and few more changes which can help begineer to get started easily.
