### ISSUE TITLE
Adding Some Relevant functionalities to Search bar.

### ISSUE THREAD

**Issue by SoumyaU25** [aslams2020/Stark-Tech-Portfolio#74]
I want to add proper functionalities to search bar . So if a user enters something to search then it will help users  to find  any content on the website quickly.
Please assign me this issue under gssoc-ext label and also provide me level for this issue.
<img width="905" alt="Screenshot 2024-10-02 141142" src="https://github.com/user-attachments/assets/5b9fbce5-0437-433c-bdc3-9fff928699c1">

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @aslams2020

**Comment by aslams2020** [comment]
We currently don't need that to be implemented.
You can still find and raise new issues
