### ISSUE TITLE
ENHANCING THE SEARCH BAR MORE EFFECTIVELY WITH ADDING ICONS AND ALL

### ISSUE THREAD

**Issue by dnyanesh99borse** [aslams2020/Stark-Tech-Portfolio#75]
**### ENHANCING THE SEARCH BAR MORE EFFECTIVELY WITH ADDING ICONS AND ALL******

I can enhance the search box of the navbar or the header by providing the search bar icon and can make it more interactive on the users interactions and will show the different attractive features on active, hover and likewise actions.

**Comment by dnyanesh99borse** [comment]
### **AS A EXPERIENCED FRONTEND DEVELOPER I HUMBLY REQUEST TO YOU TO PLEASE ASSIGN THIS TASK TO ME SO THAT I CAN ENHANCE IT MORE EFFECITVELY.**

**Comment by aslams2020** [comment]
We currently don't need that feature to be implemented
