### ISSUE TITLE
Implement Navigation for "Movies" and "Watch Video" Buttons

### ISSUE THREAD

**Issue by Blessy-B-Sherin** [aslams2020/Stark-Tech-Portfolio#78]
I noticed that the "Movies" and "Watch Video" buttons on the Stark Tech Portfolio currently do not have any navigation functionality. I would like to propose an enhancement by adding the following navigation links:

1. **Movies Button:**
   - I plan to make this button navigate to the Marvel website's Iron Man page: [Iron Man on Marvel](https://www.marvel.com/search?limit=20&query=ironman).

2. **Watch Video Button:**
   - This button will direct users to a specific YouTube video: [Watch Who is Iron Man Video](https://youtu.be/NpOgZXPWCHM?si=93wjZazo4dnSFqYx).

**Comment by aslams2020** [comment]
Assigned to someone else #8
