### ISSUE TITLE
Add New Font Family to Project

### ISSUE THREAD

**Issue by archanasingh11** [aslams2020/Stark-Tech-Portfolio#79]
We need to add a new font family to improve the overall design and typography of the application. The chosen font should align with the project’s style guidelines and enhance readability.

Please @aslams2020 assign me this task with label "GSSOC-Ext" , "Hacktoberfest-accepted" and "level1" .

**Comment by pameladeysarkar2003** [comment]
please assiign me with the task @aslams2020

**Comment by aslams2020** [comment]
We currently don't need that to be implemented.
You can still find and raise new issues
