### ISSUE TITLE
Add an extra page for Movies and Watch Videos 

### ISSUE THREAD

**Issue by t1nt1n-s0lv3r** [aslams2020/Stark-Tech-Portfolio#8]
![1oscp](https://github.com/user-attachments/assets/21afb88a-b6f1-42ce-b0aa-78e721796ce0)
As these buttons are not redirecting to a new page , I would like to contribute by adding new pages for Iron Man movies and some of his iconic clips from the past films in Avengers in watch video 

Could you please assign me this task @aslams2020 
This is my first time contributing

could u assign it under gssoc extd 24 and hacktoberfest please

**Comment by aslams2020** [comment]
@t1nt1n-s0lv3r Great! You can start working on it.

**Comment by aslams2020** [comment]
@t1nt1n-s0lv3r Any updates?

**Comment by t1nt1n-s0lv3r** [comment]
i am done with movies list and i am working on the videos part now

**Comment by t1nt1n-s0lv3r** [comment]
@aslams2020 brother can you check my pr
