### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [aslams2020/Stark-Tech-Portfolio#80]
<img width="684" alt="Screenshot 2024-10-02 at 4 11 08 PM" src="https://github.com/user-attachments/assets/8231fa15-3933-4e9c-8439-a40e03424fce">

The UI of this can be improved , can u assign me this and label itaswell.
Thank you!

**Comment by aslams2020** [comment]
Assigned to #5
