### ISSUE TITLE
Wanted to add footer section in the website

### ISSUE THREAD

**Issue by akshattiwarii** [aslams2020/Stark-Tech-Portfolio#81]
Please assign me to do this for more user friendly website

**Comment by aslams2020** [comment]
Please Elaborate more about the idea about footer.

**Comment by akshattiwarii** [comment]
![Screenshot from 2024-10-02 16-44-14](https://github.com/user-attachments/assets/526c9b99-aeb9-432a-9073-d116a371b8cc)

This type of feature I wanted to say !

**Comment by Rashidaga18** [comment]
Pls assign this task to me adding footer section in the website with lables

**Comment by aslams2020** [comment]
@akshattiwarii Assigning you. Please Add only relevant links in the footer.  Not links mentioned in the above image.

**Comment by aslams2020** [comment]
Will give level based on the work.

**Comment by akshattiwarii** [comment]
ohk thanks
