### ISSUE TITLE
Improvement in SEO

### ISSUE THREAD

**Issue by Vyshnavi1322** [aslams2020/Stark-Tech-Portfolio#82]
The portfolio lacks meta tags and proper structure for Search Engine Optimization (SEO). Assign me this

**Comment by aslams2020** [comment]
Go ahead.

**Comment by aslams2020** [comment]
@Vyshnavi1322 Any updates?

**Comment by Vyshnavi1322** [comment]
I will do it by tomorrow pls excuse me for that

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @aslams2020

**Comment by aslams2020** [comment]
@Vyshnavi1322 I'm closing this PR. Thankyou
You can still find and raise new issues
