### ISSUE TITLE
Scroll bar

### ISSUE THREAD

**Issue by S7viks** [aslams2020/Stark-Tech-Portfolio#83]
Can improve scroll bar, making it smoother
![image](https://github.com/user-attachments/assets/07cf2691-fb8e-4914-a7a6-adc1680a2d6e)

Please add gssoc extendend and level tags

**Comment by aslams2020** [comment]
Please elaborate.

**Comment by S7viks** [comment]
So there is a bit of lag with the animations and the scroll bar, we can solve this by making the scroll bar move smoother and triggering the actions based on that.

**Comment by aslams2020** [comment]
Ok, Make sure it's not too smooth that it creates problem with scrolling.
Go ahead

**Comment by S7viks** [comment]
Please add level label too

**Comment by sanjanasp786** [comment]
i would like to work on this isssue..lease assigne it to me

**Comment by abhishekkrjha2811** [comment]
i want to work on this issue plz assign it to me

**Comment by Karan-Mahato** [comment]
I would like to work on this issue, please assign this issue to me

**Comment by aslams2020** [comment]
@S7viks Are u going to work on this? as i can see you unassigned yourself. 
Tell me, so that i can assign others

**Comment by S7viks** [comment]
Please assign this to others

**Comment by aslams2020** [comment]
@sanjanasp786 Are u willing to work on this ?

**Comment by sanjanasp786** [comment]
@aslams2020 yes sir

**Comment by aslams2020** [comment]
OKAY, Assigning you. 
Ask if any doubts regarding the task.

**Comment by aslams2020** [comment]
@sanjanasp786 any updates ? Or should i close the issue?  

let me know

**Comment by aslams2020** [comment]
Closed due to no response and inactivity
