### ISSUE TITLE
Feat : ADD NEW PAGE OF MOVIES LIST AFTER CLICK MOVIES BUTTON

### ISSUE THREAD

**Issue by AbhinaySngh** [aslams2020/Stark-Tech-Portfolio#84]
![image](https://github.com/user-attachments/assets/7e6134aa-4ed7-40a0-8ea3-3cba60520ed4)

**Comment by AbhinaySngh** [comment]
@aslams2020 Please assign me this issue under gssoc-ext and hactoberfest label.

**Comment by aslams2020** [comment]
Already assigned to someone else.

You can still find another issue
