### ISSUE TITLE
Feature: Add a section for videos and stickers on the website.

### ISSUE THREAD

**Issue by ishakatiyar06** [aslams2020/Stark-Tech-Portfolio#87]
We can add a section which shows small clips of Ironman, to make it more user interactive.

**Comment by aslams2020** [comment]
Impressive. Can you please give more details and some example ?

**Comment by aslams2020** [comment]
Yeah will assign u....its just that i want to know your idea

**Comment by ishakatiyar06** [comment]
![Screenshot 2024-10-02 190848](https://github.com/user-attachments/assets/37f00550-828f-4b81-88d2-f4689272c385)
This is what I am trying to say. I hope you liked it. Do let me know.

**Comment by ishakatiyar06** [comment]
This one is just for demo purpose. I will add the downloaded and offline videos.

**Comment by aslams2020** [comment]
I mean, We will add a section in the Home page right? Above The Contact us section we can add this section

**Comment by sambedan1** [comment]
I will create a dedicated section where users can easily view and interact with videos and stickers. This section will be designed to be visually appealing and user-friendly, ensuring that it aligns with the overall website layout.

Please assign this task to me so I can implement this feature!

**Comment by ishakatiyar06** [comment]
Hey @aslams2020 , What's your thoughts on indea? Are we proceeding with it. If yes, please assign it to me.

**Comment by aslams2020** [comment]
@ishakatiyar06 
Yes, we will proceed with ur idea. 
Just For reference attaching an image : 
![image](https://github.com/user-attachments/assets/1b1e356e-6444-4dcb-a04e-0117103f6882)


go ahead!

**Comment by aslams2020** [comment]
Will assign the level based on the work. So dw abt it.

**Comment by ishakatiyar06** [comment]
Okay great.

**Comment by aslams2020** [comment]
@ishakatiyar06 Are you still willing to work on it. 
Let me know

**Comment by ishakatiyar06** [comment]
Yeah ofcourse.. But I didn't see the repository for some times.

**Comment by ishakatiyar06** [comment]
Yes, I will do it.

**Comment by aslams2020** [comment]
Okay, please try to complete sooner.

**Comment by ishakatiyar06** [comment]
Hey, I have one more idea, we can also add the links for ironman merchandise, along with this?. Should we work on it? i will try to do it asap.

**Comment by aslams2020** [comment]
For now, you can implement the assigned issue.
Later, You can raise the new issue for this idea, we will discuss there?

**Comment by ishakatiyar06** [comment]
Okay.
