### ISSUE TITLE
Improvement in Font

### ISSUE THREAD

**Issue by 5hreyanshPandey** [aslams2020/Stark-Tech-Portfolio#88]
I want to improve the font-style in the website, according to the theme of the website. So can you assign me this issue.

**Comment by sambedan1** [comment]
I will select a more modern and readable font that aligns with the overall design of the site. This includes adjusting font sizes, weights, and line spacing to improve clarity and visual appeal.

Please assign this task to me so I can implement these improvements!

**Comment by Ishajain0** [comment]
Please assign this task to me I would like to work on it....

**Comment by Ishajain0** [comment]
@aslams2020 please assign this task to me I would like to work on it...

**Comment by DarakshanSaara** [comment]
@aslams2020 Could you assign this issue to me as I can improve its font

**Comment by pameladeysarkar2003** [comment]
please assign mw with the task @aslams2020
