### ISSUE TITLE
even hover on navbar

### ISSUE THREAD

**Issue by shraddhabaghel** [aslams2020/Stark-Tech-Portfolio#89]
there is a uneven hover on navbar like home section has permanent color on it , rest hover on touch, i have fixed the issue so please assign me this

**Comment by sambedan1** [comment]
I will implement engaging hover effects on the navbar items to make them visually appealing and provide feedback when users interact with them. This includes changing colors, adding underlines, or applying subtle animations.

Please assign this task to me so I can enhance the navbar experience!

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @aslams2020
