### ISSUE TITLE
Can  work on its footer and Can add more card for insights 

### ISSUE THREAD

**Issue by Vijitverm1234** [aslams2020/Stark-Tech-Portfolio#91]
I can make cool cards which can add more  catchy insights
I will work in its footer , its quite weak , can make it catchy and resonating with its color code

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @aslams2020

**Comment by Vijitverm1234** [comment]
@aslams2020 , I am ready with some idea , when assigned with in a day , i can implement it
