### ISSUE TITLE
Contents are not center aligned

### ISSUE THREAD

**Issue by Saloni3494** [aslams2020/Stark-Tech-Portfolio#93]
![image](https://github.com/user-attachments/assets/9b17e9fc-f13d-4edf-a640-15773bb007f9)

The contents are not center aligned

**Comment by Saloni3494** [comment]
I can make it center aligned and also make the styling more effective, please assign this issue to me

**Comment by sambedan1** [comment]
I will adjust the margins and padding as needed to create a balanced layout. Additionally, I will test the alignment on various screen sizes to ensure consistency across devices.

Please assign this task to me so I can resolve the issue!

**Comment by Ishajain0** [comment]
@aslams2020 please assign this task to me....

**Comment by pameladeysarkar2003** [comment]
please assign me with task @aslams2020

**Comment by aslams2020** [comment]
@pameladeysarkar2003 did you understand what i told ?

**Comment by aslams2020** [comment]
https://github.com/aslams2020/Stark-Tech-Portfolio/issues/179#issuecomment-2395306609

I told you please don't spam. Before 30mins you did this in 20+ issues.
and still you are again and again doing it
