### ISSUE TITLE
Make website Responsive in mobile view

### ISSUE THREAD

**Issue by Abhishek2634** [aslams2020/Stark-Tech-Portfolio#95]
<img width="323" alt="Screenshot 2024-10-02 at 10 37 32 PM" src="https://github.com/user-attachments/assets/48d53450-268c-49c7-b4e7-8481eaddc9ba">

@aslams2020  I want to make the website responsive by adding media queries. please assign this issue to me under gssoc, hacktoberfest label.

**Comment by aslams2020** [comment]
@Abhishek2634 Go ahead.
