### ISSUE TITLE
Redesign Contact Page with Enhanced Styling and High-Tech Elements

### ISSUE THREAD

**Issue by itishacodes** [aslams2020/Stark-Tech-Portfolio#96]
The current contact page is very basic with minimal CSS. 
To align it with the sleek, modern theme of the Stark Tech Portfolio, I suggest the following improvements:

> Redesign the contact form with more stylish borders, shadows, and rounded corners.
> Add interactive hover effects to buttons and input fields to enhance the user experience.
> Include high-tech icons (for email, phone, etc.) to match the Stark Industries theme.
> Improve the background with a subtle gradient or texture that reflects the futuristic design.

These changes will give the contact page a modern, futuristic feel, in line with the rest of the site.

Please assign me this issue under GSSoC'24 EXTENDED and HACKTOBERFEST.

**Comment by pameladeysarkar2003** [comment]
please assign me with this task @aslams2020

**Comment by aslams2020** [comment]
@itishacodes Make sure to follow the website theme.
Assigning you

**Comment by aslams2020** [comment]
Level will be given based on the work.

**Comment by itishacodes** [comment]
Thanks @aslams2020 for assigning me. I will work as per the website theme and try my best to make it look better.

**Comment by aslams2020** [comment]
@itishacodes Are u working on it? 
let me know pls

**Comment by aslams2020** [comment]
@itishacodes Will wait till tomorrow, otherwise will have to close it due to late response.

**Comment by aslams2020** [comment]
Closed due to inactivity and no response
