### ISSUE TITLE
Updating the Contact form 

### ISSUE THREAD

**Issue by NishantK-07** [aslams2020/Stark-Tech-Portfolio#97]
![Screenshot 2024-10-02 234135](https://github.com/user-attachments/assets/e364c469-c5c6-408a-83c5-f1a214fca2d4)
The contact page can be updated ..making it more interactive and user friendly

**Comment by NishantK-07** [comment]
I want to contribute to this issue please assign this project to me under Gssoc Extended

**Comment by Munazir151** [comment]
Assign it to me

**Comment by Ishajain0** [comment]
PLEASE ASSIGN THIS TAKE TO ME . I WOULD LIKE TO WORK ON IT...

**Comment by Ishajain0** [comment]
@aslams2020 PLEASE ASSIGN THIS TAKE TO ME . I WOULD LIKE TO WORK ON IT...

**Comment by pameladeysarkar2003** [comment]
please assign me with this task @aslams2020
