### ISSUE TITLE
Inconsistent Font Sizes Across Sections

### ISSUE THREAD

**Issue by T-Fathima** [aslams2020/Stark-Tech-Portfolio#98]
The font sizes should be consistent across sections to maintain a uniform and balanced design.

**Proposed Solution:**
Ensure consistent font sizes across all sections by setting a base font size in the CSS and adjusting individual sections as necessary. Use relative units like rem to maintain responsiveness.

**Request for Assignment:**
@aslams2020 Please assign this issue to me under gssoc-ext'24. I would like to work on resolving it.
![Screenshot 2024-10-03 001605](https://github.com/user-attachments/assets/45d4af2f-367d-498b-b43a-8c879ed0c1fc)

**Comment by pameladeysarkar2003** [comment]
please assign me with this task @aslams2020
